/* Ranked from Bad Tölz (47.761, 11.559). OSRM 2026-08-14, light traffic.
   Weekend mornings add 10–20 min. Alpspitze uses B13/Walchensee (Grainau
   proxy 55 min) — not the 2h+ OSRM glitch via mountain tracks. */
window.ROUTES = [
  {
    id: "benediktenwand",
    rank: 1,
    overGrade: false,
    name: "Rampen-Rippe",
    wall: "Benediktenwand Nord",
    massif: "Bayerische Voralpen",
    day: "sat",
    dayLabel: "Sat · default · closest N wall",
    drive: "0:20–0:35",
    via: "B472 / Benediktbeuern / Tutzinger Hütte",
    aspect: "N",
    grade: "UIAA 4+",
    gradeNote: "13 pitches / ~470 m. Crux is the last pitch. Direct rib has 6–7 — stay on the original 4+.",
    pitchCount: 13,
    pitches: "13 / ~470 m",
    protection: "alpine",
    protectionNote: "Mixed bolts / pins / terrain. Not a sport grid.",
    why: "The Tölz Hausberg north wall. Twenty-five minutes, true north, grade under the cap. This is the Saturday default now that home is Bad Tölz, not Munich.",
    approach: "Bike or hike to Tutzinger Hütte from Alpenwarmbad Benediktbeuern or Jachenau. Entry almost behind the hut.",
    descent: "Alpine walk-off to the hut.",
    gear: ["60 m rope", "8–10 draws", "Slings, basic nuts/friends", "Helmet"],
    weekend: "Saturday default. Lower than Alpspitze — still warm, but shade and the short drive win.",
    dont: ["Climb the direct rib (6–7)", "Expect Osterfelder-cool air"],
    neighbor: "Maximiliansweg is the 3− easy classic. Meiser-Wülfert is the 4− on the left north face.",
    topoPage: "https://www.bergsteigen.com/touren/klettern/rampen-rippe-benediktenwand/",
    topoImg: "assets/topos/rampen-rippe-overview.jpg",
    wallImg: "assets/topos/rampen-rippe-overview.jpg",
    map: "https://www.openstreetmap.org/#map=15/47.654/11.467"
  },
  {
    id: "rotspitz",
    rank: 2,
    overGrade: false,
    name: "Hosentöter",
    wall: "Rotspitz Nordwand",
    massif: "Rofan / Achensee",
    day: "sat",
    dayLabel: "Sat · high + 46 min closer",
    drive: "0:50–1:10",
    via: "B13 / Achenpass / Rofanbahn",
    aspect: "N",
    grade: "5b",
    gradeNote: "All three pitches 5b. Nürnberger Weg 6b. Schattendasein 7b — over grade.",
    pitchCount: 3,
    pitches: "3 / 65 m",
    protection: "mixed",
    protectionNote: "Bolts + larger cams.",
    why: "From Tölz the Achenpass cuts almost 50 minutes vs Munich. High limestone, true north, short if storms sneak in.",
    approach: "Rofanbahn → west toward Rotspitz, ~45–60 min. North entries around the corner from the east face.",
    descent: "Rappel Schattendasein. Confirm last Bahn.",
    gear: ["60 m double/twin", "10 draws", "Larger cams", "Helmet"],
    weekend: "Saturday high-cool pick. Do not open the south-face topo.",
    dont: ["Say Rofan without naming the north sector", "Climb Schattendasein (7b)"],
    neighbor: "Rebitschkante is the east wall — morning sun.",
    topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/rotspitz/",
    topoImg: "assets/media/897d6bd95769.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=14/47.452/11.763"
  },
  {
    id: "maximiliansweg",
    rank: 3,
    overGrade: false,
    name: "Maximiliansweg",
    wall: "Benediktenwand Nord",
    massif: "Bayerische Voralpen",
    day: "sat",
    dayLabel: "Sat · very easy N",
    drive: "0:20–0:35",
    via: "B472 / Tutzinger Hütte",
    aspect: "N",
    grade: "UIAA 3−",
    gradeNote: "The easy classic next to Rampe-Rippe. Mostly a path through grass and schrofen.",
    pitchCount: 6,
    pitches: "long easy alpine / ~350 m",
    protection: "alpine",
    protectionNote: "Sparse. Not well-protected sport.",
    why: "Closest north wall, lowest grade. Only if the party wants a gentle alpine day twenty minutes from home.",
    approach: "Tutzinger Hütte, minutes to the entries.",
    descent: "Normal routes / hut.",
    gear: ["Rope", "Few slings", "Helmet"],
    weekend: "Saturday if 4+ still feels like a lot. Same hut as Rampen-Rippe.",
    dont: ["Call it well-protected sport", "Underestimate grass / route-finding"],
    neighbor: "Rampen-Rippe if 4+ is OK.",
    topoPage: "https://www.thecrag.com/en/climbing/germany/route/4024450425",
    topoImg: "assets/topos/rampen-rippe-overview.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.654/11.467"
  },
  {
    id: "nebelgespenst",
    rank: 4,
    overGrade: false,
    name: "Nebelgespenst",
    wall: "Nodlwand / Alpspitze",
    massif: "Wetterstein",
    day: "sat",
    dayLabel: "Sat · high + grade 4",
    drive: "0:55–1:15",
    via: "B13 / Walchensee / Alpspitzbahn",
    aspect: "E",
    grade: "UIAA 4",
    gradeNote: "5 pitches at 4. Bolted 2022 for first alpine MSL days.",
    pitchCount: 5,
    pitches: "5 / ~150–160 m",
    protection: "alpine-bolted",
    protectionNote: "Two bolts at stands; intermediates partly bolted. 60 m to rappel.",
    why: "Perfect grade. High and cool. From Tölz via Walchensee, not the Munich A95 crawl. East: morning sun, afternoon shade.",
    approach: "Osterfelderkopf → 15 min / 70 Hm under the Nodlwand, right of the Ferrata.",
    descent: "Rappel (60 m) or walk to Ferrata / Nordwandsteig. Last Bahn 17:30 Jul–Sep.",
    gear: ["60 m rope", "12 draws", "Helmet"],
    weekend: "Saturday. Easy add-on near BW3. Sunday = lift + storms.",
    dont: ["Treat east as all-day shade", "Miss the last Bahn"],
    neighbor: "Nodlsuppn is the sister line on the same wall.",
    topoPage: "https://bergparadiese.de/nebelgespenst-mehrseillaengen-kletterei-an-der-nodlwand-alpspitze",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.427/11.051"
  },
  {
    id: "buchstein-nordkante",
    rank: 5,
    overGrade: false,
    name: "Nordkante",
    wall: "Buchstein Nord",
    massif: "Bayerische Voralpen / Tegernsee",
    day: "sun",
    dayLabel: "Sun default · 35 min",
    drive: "0:35–0:50",
    via: "B13 / Kreuth / Klamm",
    aspect: "N",
    grade: "UIAA 5",
    gradeNote: "Three pitches. Classic crack then a steep corner. Hut page calls it a beautiful 5.",
    pitchCount: 3,
    pitches: "3 / ~80–90 m",
    protection: "alpine",
    protectionNote: "Not a sport grid. Nuts and friends fit the crack. Stands exist.",
    why: "True north, three pitches, 35 minutes from Tölz. New Sunday default — closer and shadier than Kampenwand.",
    approach: "Tegernseer Hütte. Walk north toward Buchsteinhütte; entry where the NW wall turns onto the north face. First pin is high in a crack.",
    descent: "Through the pines over the summit, then the Heckmair II chimney back to the hut.",
    gear: ["60 m rope", "Draws + nuts/friends", "Slings", "Helmet"],
    weekend: "Sunday morning. Down by 13:00. Hut breakfast if you slept there.",
    dont: ["Wander onto the south face (heat)", "Treat UIAA 5 as a gym 5"],
    neighbor: "Zauberrippe is the 6 next door. Simplinella is the 4 practice line on the NW wall.",
    topoPage: "https://tegernseerhuette.de/bewegen",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.626/11.801"
  },
  {
    id: "rabnhoamat",
    rank: 6,
    overGrade: false,
    name: "Rabnhoamat",
    wall: "Obere Wettersteinspitze / Gamsanger",
    massif: "Wetterstein",
    day: "sat",
    dayLabel: "Sat · north 6−",
    drive: "0:55–1:10",
    via: "B13 / Mittenwald / Ferchensee",
    aspect: "N",
    grade: "UIAA 6−",
    gradeNote: "A few 6− bits; rest easier stepped wall. Fits the cap.",
    pitchCount: 9,
    pitches: "~250 m",
    protection: "alpine-bolted",
    protectionNote: "Enough bolts; stands rappel-ready. Small nuts + slings useful.",
    why: "True north, well bolted alpine, lake swim after. From Tölz Mittenwald is under an hour.",
    approach: "Bike toward Ferchensee/Schachen, depot ~1260 m, then 30 min into the kar. Or bus to Ferchensee + hike.",
    descent: "Rappel the route (60 m doubles).",
    gear: ["60 m double", "10 draws", "Small nuts", "Slings", "Helmet"],
    weekend: "Saturday. Combine with a dip in Ferchensee. Less Bahn-circus than Alpspitze.",
    dont: ["Treat the 6− as a gym 6− — it's alpine", "Leave the doubles at home"],
    neighbor: "Swim + hut food at Ferchensee / Lautersee.",
    topoPage: "https://www.bergsteigen.com/touren/klettern/rabnhoamat/",
    topoImg: "assets/media/6194a39bf3c6.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=14/47.435/11.256"
  },
  {
    id: "alpspitze",
    rank: 7,
    overGrade: "partial",
    name: "BW3",
    wall: "Alpspitze NO / Nord",
    massif: "Wetterstein",
    day: "sat",
    dayLabel: "Sat · high · climb BW3 only",
    drive: "0:55–1:15",
    via: "B13 / Walchensee / Alpspitzbahn",
    aspect: "N / NE",
    grade: "UIAA 4",
    gradeNote: "BW3 is 4. Alpspitz-Plaisir is 6+ obligatory — over grade. Adamplatte is 3–4 alpine/runout.",
    pitchCount: 5,
    pitches: "several (BW3 sockel)",
    protection: "alpine-bolted",
    protectionNote: "BW3 is the bolt-friendlier sockel. Adamplatte is not sport.",
    why: "High, cool, short approach from the Bahn. From Tölz take B13, not A95. Stay on BW3.",
    approach: "Osterfelderkopf, 20–30 min Nordwandsteig. Bahn 08:00–17:30 Jul–Sep.",
    descent: "Ostgrat + Nordwandsteig. Do not rappel onto the trail.",
    gear: ["50–60 m rope", "12–14 draws", "Helmet"],
    weekend: "Saturday. Sunday = lift + storms = skip.",
    dont: ["Climb Alpspitz-Plaisir (6+ obl)", "Treat Adamplatte as sport", "Miss the last Bahn"],
    neighbor: "Nebelgespenst on the Nodlwand is the easier bolted 4.",
    topoPage: "https://www.bergsteigen.com/touren/klettern/adamplatte-bw3-alpspitze/",
    topoImg: "assets/topos/alpspitze-overview.jpg",
    wallImg: "assets/media/4b5a0b0a05c5.jpg",
    map: "https://www.openstreetmap.org/#map=15/47.440/11.050"
  },
  {
    id: "geiselstein",
    rank: 8,
    overGrade: false,
    name: "Herzogweg",
    wall: "Geiselstein Nordwand",
    massif: "Ammergauer Alpen",
    day: "sat",
    dayLabel: "Sat · long alpine",
    drive: "1:10–1:25",
    via: "B472 / Weilheim / Halblech",
    aspect: "N",
    grade: "UIAA 5 / 5+",
    gradeNote: "First pitch often feels 6−, polished. Middle easier.",
    pitchCount: 17,
    pitches: "~17 / 400–500 m",
    protection: "alpine",
    protectionNote: "Stands + key bolts. Friends/slings useful, not mandatory.",
    why: "The Ammergau summer north wall. Twenty minutes closer than from Munich. Long, shady, moderate. Not sport.",
    approach: "Park Halblech, bike toward Kenzenhütte, leave bikes at Wankerfleck. ~45 min + 10 min under the face. Plan 6–7 h minimum.",
    descent: "Down-climb the normal route (UIAA II), ~60–70 min to the bike cache.",
    gear: ["60 m rope", "10 draws", "Slings + a few friends", "3 L water"],
    weekend: "Saturday only. Take Panico Ammergau — no complete free drawn topo.",
    dont: ["Call it plaisir", "Attempt Sunday", "Go without a real topo"],
    neighbor: "Ballisto on the south face is a heat-reject.",
    topoPage: "https://www.hikr.org/tour/post155013.html",
    topoImg: "assets/media/4b5a0b0a05c5.jpg",
    wallImg: "assets/media/6a69a05f82d8.jpg",
    map: "https://www.openstreetmap.org/#map=15/47.598/10.825"
  },
  {
    id: "rebitschkante",
    rank: 9,
    overGrade: false,
    name: "Rebitschkante",
    wall: "Rotspitz Ostwand",
    massif: "Rofan / Achensee",
    day: "sat",
    dayLabel: "Sat early · east",
    drive: "0:50–1:10",
    via: "B13 / Achenpass / Rofanbahn",
    aspect: "E",
    grade: "5b / 4c obl.",
    gradeNote: "Two pitches: 5b then 4c.",
    pitchCount: 2,
    pitches: "2 / 70 m",
    protection: "mixed",
    protectionNote: "Sanierte classic.",
    why: "High, short, moderate. Not north. Pair with Hosentöter if you want shade after.",
    approach: "Rofanbahn → Rotspitz ~45 min.",
    descent: "Normal route from the summit.",
    gear: ["60 m double", "10 draws", "Helmet"],
    weekend: "Only very early Saturday.",
    dont: ["Start at noon", "Confuse with Rotspitz Süd"],
    neighbor: "Hosentöter is the north-face pick on the same peak.",
    topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/rotspitz/",
    topoImg: "assets/media/5e8c47ef9ff1.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=14/47.452/11.763"
  },
  {
    id: "zauberrippe",
    rank: 10,
    overGrade: false,
    name: "Zauberrippe",
    wall: "Buchstein Nordwand",
    massif: "Bayerische Voralpen / Tegernsee",
    day: "sun",
    dayLabel: "Sun · north 6",
    drive: "0:35–0:50",
    via: "B13 / Kreuth / Tegernseer Hütte",
    aspect: "N",
    grade: "UIAA 6",
    gradeNote: "Three pitches. Hut page says 6, and that 6+ / 7− would not be a lie. At the cap.",
    pitchCount: 3,
    pitches: "3 / ~90 m",
    protection: "alpine-bolted",
    protectionNote: "Bolted enough to follow; not a gym grid. Metal name plate at the start.",
    why: "True north, 35 minutes, at the grade cap. The best 6 on the Tölz-local north faces.",
    approach: "From the hut, north toward Buchsteinhütte. Leave the road at the first sharp left onto a path along the wall. Entry at a small prow with a fixed rope and a name plate. Aim for the inverted-L crack.",
    descent: "Plateau, through pines, over the summit to the hut.",
    gear: ["60 m rope", "10 draws", "Slings", "Helmet"],
    weekend: "Sunday if 6 is on. Else Nordkante.",
    dont: ["Sandbag this as a friendly gym 6", "Start it after 11:00 on a storm Sunday"],
    neighbor: "Nordkante is the 5 next door.",
    topoPage: "https://tegernseerhuette.de/bewegen",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.627/11.800"
  },
  {
    id: "meiser-wuelfert",
    rank: 11,
    overGrade: false,
    name: "Meiser-Wülfert",
    wall: "Benediktenwand Linke Nordwand",
    massif: "Bayerische Voralpen",
    day: "sat",
    dayLabel: "Sat · historic N 4−",
    drive: "0:20–0:35",
    via: "B472 / Tutzinger Hütte",
    aspect: "N",
    grade: "UIAA 4−",
    gradeNote: "1907 classic. DAV hut notes ~2.5 hours from the entry. Left north face, not the Rampe sector.",
    pitchCount: 8,
    pitches: "several / ~230 m wall",
    protection: "alpine",
    protectionNote: "Old-school. Pins and terrain. Not plaisir.",
    why: "Same 25-minute north wall, quieter than Rampe-Rippe, grade a notch easier.",
    approach: "Tutzinger Hütte, then left along the north face (Linke Nordwand). Longer walk than Rampe-Rippe.",
    descent: "Alpine walk-off / hut.",
    gear: ["60 m rope", "Draws, slings, nuts", "Helmet"],
    weekend: "Saturday if Rampe-Rippe is queued.",
    dont: ["Expect a bolt grid", "Confuse with Direkte Rippe (7)"],
    neighbor: "Rampen-Rippe is the popular 4+ in the central wall.",
    topoPage: "https://www.thecrag.com/en/climbing/germany/area/4024378071",
    topoImg: "assets/topos/rampen-rippe-overview.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.655/11.462"
  },
  {
    id: "hoellentorkopf",
    rank: 12,
    overGrade: false,
    name: "Nordkante",
    wall: "Höllentorkopf",
    massif: "Wetterstein",
    day: "sat",
    dayLabel: "Sat Plan B",
    drive: "0:55–1:15",
    via: "B13 / same Bahn as Alpspitze",
    aspect: "N",
    grade: "UIAA 4+",
    gradeNote: "Place 5−. 14 pitches. Route-finding errors are common.",
    pitchCount: 14,
    pitches: "14 / ~480 m",
    protection: "alpine",
    protectionNote: "Most stands bolted. Not bolts every 2 m.",
    why: "Same logistics as Alpspitze. Moderate alpine ridge. From Tölz via Walchensee.",
    approach: "Alpspitzbahn → Hupfleitenjoch / Knappenhäuser, then left through pines. Budget real approach time.",
    descent: "Höllentor → Osterfelder. Last Bahn 17:30.",
    gear: ["60 m rope", "Draws, slings, basic friends", "Helmet", "Headlamp if slow"],
    weekend: "Saturday. Not a Sunday storm-day route.",
    dont: ["Call it plaisir", "Underestimate upper schrofen"],
    neighbor: "Take the Deichjodler 2025 topo.",
    topoPage: "https://www.deichjodler.com/2020/09/hoellentorkopf-nordkante/",
    topoImg: "assets/media/71165d0d2a10.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.435/11.045"
  },
  {
    id: "kampenwand",
    rank: 13,
    overGrade: false,
    name: "Nordwand (Zeller)",
    wall: "Kampenwand Nordgipfel",
    massif: "Chiemgauer Alpen",
    day: "sun",
    dayLabel: "Sun east · short",
    drive: "1:00–1:20",
    via: "B472 / A8 / Kampenwandbahn",
    aspect: "N",
    grade: "UIAA 5−",
    gradeNote: "Two pitches, 4+ / 5−.",
    pitchCount: 2,
    pitches: "2 / 75 m",
    protection: "alpine",
    protectionNote: "Pins + bolts. E3. No extra gear required.",
    why: "Still a clean Sunday-east short north. Same drive as from Munich — no Tölz bonus. Buchstein is closer.",
    approach: "Bahn to Bergstation, under the Kaisersäle left to the north entries.",
    descent: "One 30 m rap into the Kaisersäle. No loose rock onto people.",
    gear: ["60 m rope", "Draws", "Helmet"],
    weekend: "Sunday morning if you want east-of-Tölz. Down by 13:00.",
    dont: ["Wander onto the Südwände", "Call the Überschreitung well-protected sport"],
    neighbor: "Mechanikerkante is the 5+ neighbor.",
    topoPage: "https://sebastian-steude.de/klettern/routen/kampenwand-nordgipfel-nordwand/",
    topoImg: "assets/media/be9b23a777cd.webp",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.757/12.367"
  },
  {
    id: "winklerfuehre",
    rank: 14,
    overGrade: false,
    name: "Winklerführe",
    wall: "Benediktenwand Nord",
    massif: "Bayerische Voralpen",
    day: "sat",
    dayLabel: "Sat · easy N 3+",
    drive: "0:20–0:35",
    via: "B472 / Tutzinger Hütte",
    aspect: "N",
    grade: "UIAA 3+",
    gradeNote: "300 m trad. FA M. Winkler. Between Maximiliansweg and Rampe-Rippe.",
    pitchCount: 9,
    pitches: "~300 m",
    protection: "alpine",
    protectionNote: "Trad / alpine. Not a bolt grid.",
    why: "Another Tölz-doorstep north line if Rampe-Rippe is busy and 4+ is more than you want.",
    approach: "Tutzinger Hütte, Rampe-Rippe sector.",
    descent: "Walk-off / Maximiliansweg terrain.",
    gear: ["60 m rope", "Slings, nuts", "Helmet"],
    weekend: "Saturday easy-north alternative.",
    dont: ["Call it sport", "Underestimate grass"],
    neighbor: "Maximiliansweg is even easier (3−).",
    topoPage: "https://www.thecrag.com/en/climbing/germany/route/4024450338",
    topoImg: "assets/topos/rampen-rippe-overview.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.654/11.462"
  },
  {
    id: "schmid-mueller",
    rank: 15,
    overGrade: false,
    name: "Schmid/Müller",
    wall: "Rofanspitze Ostwand",
    massif: "Rofan / Achensee",
    day: "sat",
    dayLabel: "Sat · high east classic",
    drive: "0:50–1:10",
    via: "B13 / Achenpass / Rofanbahn",
    aspect: "E",
    grade: "UIAA 5",
    gradeNote: "First pitch often feels stiff 5; then mostly 2–4. About 4 pitches / 140 m.",
    pitchCount: 4,
    pitches: "4 / ~140 m",
    protection: "mixed",
    protectionNote: "Sanierte, not plaisir. First pitch better bolted; then spaced.",
    why: "High, famous, moderate. From Tölz this is a 50-minute drive, not 1:40. Morning sun.",
    approach: "Rofanbahn, short walk to the east face.",
    descent: "Walk off or rap a bit lower in the shade.",
    gear: ["50–60 m rope", "Draws", "Nuts/friends", "Helmet"],
    weekend: "Saturday early. East wall cooks later.",
    dont: ["Call it plaisir", "Start at noon"],
    neighbor: "Hosentöter is the north shade option on Rotspitz.",
    topoPage: "https://www.bergsteigen.com/touren/klettern/rofanspitze-ostwand-schmidmueller/",
    topoImg: "assets/topos/rotspitz.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.447/11.764"
  },
  {
    id: "silenzio",
    rank: 16,
    overGrade: false,
    name: "Silenzio",
    wall: "Scheffauer Nordwand",
    massif: "Kaisergebirge",
    day: "sat",
    dayLabel: "Sat · one pitch of 6",
    drive: "1:00–1:20",
    via: "B472 / A8 / A93 / Kaindlhütte",
    aspect: "N",
    grade: "UIAA 6",
    gradeNote: "One pitch 6 (or 5/A0) and one 5−. Mostly 3–4. Fits “only a few pitches at 6.”",
    pitchCount: 15,
    pitches: "~15 / 520 m",
    protection: "alpine-bolted",
    protectionNote: "Hard bits well bolted; easy terrain sparser. E2.",
    why: "True north, at the grade cap but only briefly. Same drive as from Munich — no Tölz shortcut.",
    approach: "Same as Ostler. Entry ~50 m left, steep crack-corner, left of nettles.",
    descent: "Widauersteig ~1 h.",
    gear: ["50 m rope", "Draws + nuts and slings", "Helmet"],
    weekend: "Saturday if you want the Kaiser. A0 the crux if you want to stay under 6.",
    dont: ["On-sight the 6 as the first pitch of a 15-pitch north face if it is your limit", "Sunday"],
    neighbor: "Ostlerführe avoids the 6 entirely.",
    topoPage: "https://www.stadler-markus.de/alpinklettern/wilder-kaiser/kletterroute/silenzio.html",
    topoImg: "assets/media/f902c2b4a4b8.jpg",
    wallImg: "assets/media/f902c2b4a4b8.jpg",
    map: "https://www.openstreetmap.org/#map=14/47.567/12.183"
  },
  {
    id: "nordwandliebe",
    rank: 17,
    overGrade: false,
    name: "Nordwandliebe",
    wall: "Scheffauer Nordwand",
    massif: "Kaisergebirge",
    day: "sat",
    dayLabel: "Sat · Kaiser north 5−",
    drive: "1:00–1:20",
    via: "B472 / A8 / A93 / Kaindlhütte",
    aspect: "N",
    grade: "UIAA 5−",
    gradeNote: "One 5− move; mostly 3–4. 3–5 hours on the face.",
    pitchCount: 14,
    pitches: "~500 m / 400 m wall",
    protection: "alpine-bolted",
    protectionNote: "E2. Bolts on the hard bits. Extra gear if 4/5− already taxes you. 50 m rope enough.",
    why: "Still a great north face — but from Tölz it is no closer than from Munich. Benediktenwand and Rofan win the drive.",
    approach: "Kaindlhütte → Riegensteig toward Zettenkaiser → left up the gully (~50 min from the hut). Entry ~50 m right of the big slab. Kaiserlift shortens the walk.",
    descent: "Summit, then north via Widauersteig (easy via ferrata) to Kaindlhütte (1.5–2 h).",
    gear: ["50 m rope", "Draws + nuts and slings", "Helmet", "Via-ferrata comfort for descent"],
    weekend: "Saturday (long) if you specifically want the Kaiser. Not the default anymore.",
    dont: ["Treat it as a 2-hour sport crag", "Stay on the face into a Sunday storm window"],
    neighbor: "Ostlerführe is easier (4). Silenzio is the same wall with one pitch of 6.",
    topoPage: "https://www.stadler-markus.de/alpinklettern/wilder-kaiser/kletterroute/nordwandliebe.html",
    topoImg: "assets/media/c66b68e70791.png",
    wallImg: "assets/media/dbd960058724.jpg",
    map: "https://www.openstreetmap.org/#map=14/47.567/12.183"
  },
  {
    id: "ostlerfuehre",
    rank: 18,
    overGrade: false,
    name: "Ostlerführe",
    wall: "Scheffauer Nordwand",
    massif: "Kaisergebirge",
    day: "sat",
    dayLabel: "Sat · long north 4",
    drive: "1:00–1:20",
    via: "B472 / A8 / A93 / Kaiserlift",
    aspect: "N",
    grade: "UIAA 4",
    gradeNote: "One short 4; mostly 3 and easier. 16 pitches. Master 3 without a gym grid.",
    pitchCount: 16,
    pitches: "16 / ~625 m",
    protection: "alpine-bolted",
    protectionNote: "Two glue-ins at stands; extra bolt at hard bits. Not plaisir spacing.",
    why: "True north, long, classic. Same Kaiser drive as Munich — keep it for the line, not the commute.",
    approach: "Kaindlhütte then ~45 min to the helipad / Widauersteig. Entry at a smooth groove-like corner. Lift from 08:30.",
    descent: "Widauersteig (easy via ferrata) to Kaindlhütte. Helmet on — rockfall.",
    gear: ["50 m rope", "8 draws", "Long slings", "Basic nuts/friends", "Helmet"],
    weekend: "Saturday only — too long for Sunday storms. After rain wait a dry day.",
    dont: ["Treat it as plaisir", "Start it Sunday"],
    neighbor: "Nordwandliebe is the better-bolted 5− next door.",
    topoPage: "https://www.bergsteigen.com/touren/klettern/ostler-fuehre-scheffauer/",
    topoImg: "assets/topos/ostler-overview.jpg",
    wallImg: "assets/topos/ostler-overview.jpg",
    map: "https://www.openstreetmap.org/#map=14/47.567/12.183"
  },
  {
    id: "nodlsuppn",
    rank: 19,
    overGrade: false,
    name: "Nodlsuppn",
    wall: "Nodlwand / Alpspitze",
    massif: "Wetterstein",
    day: "sat",
    dayLabel: "Sat · high 6−",
    drive: "0:55–1:15",
    via: "B13 / Walchensee / Alpspitzbahn",
    aspect: "E",
    grade: "UIAA 6−",
    gradeNote: "5 short pitches, 6−. Harder sister of Nebelgespenst (4).",
    pitchCount: 5,
    pitches: "5 / ~150 m",
    protection: "alpine-bolted",
    protectionNote: "Modern bolts, 60 m to rappel.",
    why: "Same cool high wall as Nebelgespenst, one notch harder, still under 6.",
    approach: "Osterfelderkopf, 15 min under the Nodlwand.",
    descent: "Rappel 60 m.",
    gear: ["60 m rope", "8 draws", "Helmet"],
    weekend: "Saturday. If 6− feels spicy, do Nebelgespenst instead.",
    dont: ["Sunday (Bahn + storms)", "Skip the 60 m rope"],
    neighbor: "Nebelgespenst is the 4 next door.",
    topoPage: "https://wetterstein-bergfuehrer.de/wp-content/uploads/2023/08/alpspitze_nodlwand_nodlsuppn_topo.pdf",
    topoImg: "assets/topos/nodlsuppn-topo.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.427/11.052"
  },
  {
    id: "kg-weg",
    rank: 20,
    overGrade: false,
    name: "KG-Weg",
    wall: "Alpspitze Nord / NO",
    massif: "Wetterstein",
    day: "sat",
    dayLabel: "Sat · alpine 4+",
    drive: "0:55–1:15",
    via: "B13 / Walchensee / Alpspitzbahn",
    aspect: "N / NE",
    grade: "UIAA 4+",
    gradeNote: "Few places 4+; mostly 3–4. More alpine than BW3.",
    pitchCount: 9,
    pitches: "several",
    protection: "alpine",
    protectionNote: "Mixed bolts — not as tight as BW3.",
    why: "Same high face, grade fits. Pick BW3 if you want more bolts.",
    approach: "Osterfelderkopf, Nordwandsteig, near BW3 / left of Alpspitz-Plaisir.",
    descent: "Ferrata or Ostgrat + Nordwandsteig.",
    gear: ["60 m rope", "Draws + slings", "Small rack", "Helmet"],
    weekend: "Saturday. Do not continue into runout Adamplatte.",
    dont: ["Confuse with Alpspitz-Plaisir (over grade)", "Miss the last Bahn"],
    neighbor: "BW3 is the bolt-friendlier sockel.",
    topoPage: "https://www.segeln-und-klettern.de/klettern/alpspitze-kg-weg/",
    topoImg: "assets/topos/alpspitze-overview.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.440/11.050"
  }
];

window.ROUTE_COORDS = {
  benediktenwand: { lat: 47.6528, lng: 11.4656 },
  rotspitz: { lat: 47.4418, lng: 11.7618 },
  maximiliansweg: { lat: 47.6536, lng: 11.4638 },
  nebelgespenst: { lat: 47.4268, lng: 11.0512 },
  "buchstein-nordkante": { lat: 47.6264, lng: 11.8012 },
  rabnhoamat: { lat: 47.4398, lng: 11.2486 },
  alpspitze: { lat: 47.4244, lng: 11.0488 },
  geiselstein: { lat: 47.5752, lng: 10.8084 },
  rebitschkante: { lat: 47.4426, lng: 11.7642 },
  zauberrippe: { lat: 47.6271, lng: 11.8004 },
  "meiser-wuelfert": { lat: 47.6544, lng: 11.4612 },
  hoellentorkopf: { lat: 47.4286, lng: 11.0442 },
  kampenwand: { lat: 47.7542, lng: 12.3668 },
  winklerfuehre: { lat: 47.6541, lng: 11.4624 },
  "schmid-mueller": { lat: 47.4468, lng: 11.7662 },
  silenzio: { lat: 47.5579, lng: 12.1796 },
  nordwandliebe: { lat: 47.5574, lng: 12.1782 },
  ostlerfuehre: { lat: 47.5568, lng: 12.1764 },
  nodlsuppn: { lat: 47.4274, lng: 11.0520 },
  "kg-weg": { lat: 47.4252, lng: 11.0506 }
};
