window.ROUTES = [
  {
    id: "nordwandliebe",
    rank: 1,
    overGrade: false,
    name: "Nordwandliebe",
    wall: "Scheffauer Nordwand",
    massif: "Kaisergebirge",
    day: "sat",
    dayLabel: "Sat · best overall",
    drive: "1:30–1:45",
    via: "A8 / A93 → Kaindlhütte",
    aspect: "N",
    grade: "UIAA 5−",
    gradeNote: "One 5− move; mostly 3–4. 3–5 hours on the face.",
    pitches: "~500 m / 400 m wall",
    protection: "alpine-bolted",
    protectionNote: "E2. Bolts on the hard bits. Extra gear if 4/5− already taxes you. 50 m rope enough.",
    why: "True north, grade under the new cap, mostly bolted, good rock. The best match now that 6+ is off the table.",
    approach: "Kaindlhütte → Riegensteig toward Zettenkaiser → left up the gully (~50 min from the hut). Entry ~50 m right of the big slab. Kaiserlift shortens the walk.",
    descent: "Summit, then north via Widauersteig (easy via ferrata) to Kaindlhütte (1.5–2 h).",
    gear: ["50 m rope", "Draws + nuts and slings", "Helmet", "Via-ferrata comfort for descent"],
    weekend: "Saturday (long). Sunday only if you start very early and are down by early afternoon.",
    dont: ["Treat it as a 2-hour sport crag", "Stay on the face into a Sunday storm window"],
    neighbor: "Ostlerführe is easier (4). Silenzio is the same wall with one pitch of 6.",
    topoPage: "https://www.stadler-markus.de/alpinklettern/wilder-kaiser/kletterroute/nordwandliebe.html",
    topoImg: "https://www.stadler-markus.de/typo3temp/assets/_processed_/c/1/csm_Scheffauer_Nordwandliebe_01_653686d628.png",
    wallImg: "https://www.stadler-markus.de/typo3temp/assets/_processed_/7/2/csm_ScheffauerNordwandliebe_94087b1efe.jpg",
    map: "https://www.openstreetmap.org/#map=14/47.567/12.183"
  },
  {
    id: "nebelgespenst",
    rank: 2,
    overGrade: false,
    name: "Nebelgespenst",
    wall: "Nodlwand / Alpspitze",
    massif: "Wetterstein",
    day: "sat",
    dayLabel: "Sat · high + grade 4",
    drive: "1:20–1:35",
    via: "A95 + Alpspitzbahn",
    aspect: "E",
    grade: "UIAA 4",
    gradeNote: "5 pitches at 4. Bolted 2022 for first alpine MSL days.",
    pitches: "5 / ~150–160 m",
    protection: "alpine-bolted",
    protectionNote: "Two bolts at stands; intermediates partly bolted. 60 m to rappel.",
    why: "Perfect grade. High and cool. East, not north — morning sun, afternoon shade. Elevation does most of the heat work.",
    approach: "Osterfelderkopf → 15 min / 70 Hm under the Nodlwand, right of the Ferrata.",
    descent: "Rappel (60 m) or walk to Ferrata / Nordwandsteig. Last Bahn 17:30 Jul–Sep.",
    gear: ["60 m rope", "12 draws", "Helmet"],
    weekend: "Saturday. Easy add-on near BW3. Sunday = lift + storms.",
    dont: ["Treat east as all-day shade", "Miss the last Bahn"],
    neighbor: "Nodlsuppn is the sister line on the same wall.",
    topoPage: "https://bergparadiese.de/nebelgespenst-mehrseillaengen-kletterei-an-der-nodlwand-alpspitze",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.440/11.050"
  },
  {
    id: "ostlerfuehre",
    rank: 3,
    overGrade: false,
    name: "Ostlerführe",
    wall: "Scheffauer Nordwand",
    massif: "Kaisergebirge",
    day: "sat",
    dayLabel: "Sat · long north 4",
    drive: "1:30–1:45",
    via: "Kufstein / Kaiserlift / e-bike",
    aspect: "N",
    grade: "UIAA 4",
    gradeNote: "One short 4; mostly 3 and easier. 16 pitches. Master 3 without a gym grid.",
    pitches: "16 / ~625 m",
    protection: "alpine-bolted",
    protectionNote: "Two glue-ins at stands; extra bolt at hard bits. Not plaisir spacing.",
    why: "True north, long, classic, grade exactly in the new band. Stands rebuilt.",
    approach: "Kaindlhütte then ~45 min to the helipad / Widauersteig. Entry at a smooth groove-like corner. Lift from 08:30.",
    descent: "Widauersteig (easy via ferrata) to Kaindlhütte. Helmet on — rockfall.",
    gear: ["50 m rope", "8 draws", "Long slings", "Basic nuts/friends", "Helmet"],
    weekend: "Saturday only — too long for Sunday storms. After rain wait a dry day.",
    dont: ["Treat it as plaisir", "Start it Sunday"],
    neighbor: "Nordwandliebe is the better-bolted 5− next door.",
    topoPage: "https://www.bergsteigen.com/touren/klettern/ostler-fuehre-scheffauer/",
    topoImg: "https://www.bergsteigen.com/fileadmin/_processed_/6/e/csm_ostler-fuehre-scheffauer-klettern-topo_2141d1752a.png",
    wallImg: "https://www.bergsteigen.com/fileadmin/_processed_/f/b/csm_wilder-kaiser-scheffauer-nordwand-klettern-uebersicht_a5790a0357.jpg",
    map: "https://www.openstreetmap.org/#map=14/47.567/12.183"
  },
  {
    id: "geiselstein",
    rank: 4,
    overGrade: false,
    name: "Herzogweg",
    wall: "Geiselstein Nordwand",
    massif: "Ammergauer Alpen",
    day: "sat",
    dayLabel: "Sat · long alpine",
    drive: "1:20–1:40",
    via: "Halblech / Wankerfleck",
    aspect: "N",
    grade: "UIAA 5 / 5+",
    gradeNote: "First pitch often feels 6−, polished. Middle easier.",
    pitches: "~17 / 400–500 m",
    protection: "alpine",
    protectionNote: "Stands + key bolts. Friends/slings useful, not mandatory.",
    why: "The Ammergau summer north wall. Long, shady, moderate. Not sport.",
    approach: "Park Halblech, bike toward Kenzenhütte, leave bikes at Wankerfleck. ~45 min + 10 min under the face. Plan 6–7 h minimum.",
    descent: "Down-climb the normal route (UIAA II), ~60–70 min to the bike cache.",
    gear: ["60 m rope", "10 draws", "Slings + a few friends", "3 L water"],
    weekend: "Saturday only. Take Panico Ammergau — no complete free drawn topo.",
    dont: ["Call it plaisir", "Attempt Sunday", "Go without a real topo"],
    neighbor: "Ballisto on the south face is a heat-reject.",
    topoPage: "https://www.hikr.org/tour/post155013.html",
    topoImg: "",
    wallImg: "https://f.hikr.org/files/3183706s.jpg",
    map: "https://www.openstreetmap.org/#map=15/47.598/10.825"
  },
  {
    id: "rotspitz",
    rank: 5,
    overGrade: false,
    name: "Hosentöter",
    wall: "Rotspitz Nordwand",
    massif: "Rofan / Achensee",
    day: "sat",
    dayLabel: "Sat · height",
    drive: "1:30–1:50",
    via: "Rofanbahn Maurach",
    aspect: "N",
    grade: "5b",
    gradeNote: "All three pitches 5b. Nürnberger Weg 6b. Schattendasein 7b — over grade.",
    pitches: "3 / 65 m",
    protection: "mixed",
    protectionNote: "Bolts + larger cams.",
    why: "Cable-car high limestone. True north sector. Short enough if storms sneak in.",
    approach: "Rofanbahn → west toward Rotspitz, ~45–60 min. North entries around the corner from the east face.",
    descent: "Rappel Schattendasein. Confirm last Bahn.",
    gear: ["60 m double/twin", "10 draws", "Larger cams", "Helmet"],
    weekend: "Saturday. Do not open the south-face topo.",
    dont: ["Say Rofan without naming the north sector", "Climb Schattendasein (7b)"],
    neighbor: "Rebitschkante is the east wall — morning sun.",
    topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/rotspitz/",
    topoImg: "https://www.climbers-paradise.com/uploads/climbers_paradise/images/resources/93112876/achensee_msl_rotspitz_nordwand_75dpi.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=14/47.452/11.763"
  },
  {
    id: "alpspitze",
    rank: 6,
    overGrade: "partial",
    name: "BW3",
    wall: "Alpspitze NO / Nord",
    massif: "Wetterstein",
    day: "sat",
    dayLabel: "Sat · high · climb BW3 only",
    drive: "1:20–1:35",
    via: "A95 + Alpspitzbahn",
    aspect: "N / NE",
    grade: "UIAA 4",
    gradeNote: "BW3 is 4. Alpspitz-Plaisir is 6+ obligatory — over grade. Adamplatte is 3–4 alpine/runout.",
    pitches: "several (BW3 sockel)",
    protection: "alpine-bolted",
    protectionNote: "BW3 is the bolt-friendlier sockel. Adamplatte is not sport.",
    why: "High, cool, short approach. Stay on BW3. Do not continue into Alpspitz-Plaisir.",
    approach: "Osterfelderkopf, 20–30 min Nordwandsteig. Bahn 08:00–17:30 Jul–Sep.",
    descent: "Ostgrat + Nordwandsteig. Do not rappel onto the trail.",
    gear: ["50–60 m rope", "12–14 draws", "Helmet"],
    weekend: "Saturday. Sunday = lift + storms = skip.",
    dont: ["Climb Alpspitz-Plaisir (6+ obl)", "Treat Adamplatte as sport", "Miss the last Bahn"],
    neighbor: "Nebelgespenst on the Nodlwand is the easier bolted 4.",
    topoPage: "https://www.bergsteigen.com/touren/klettern/adamplatte-bw3-alpspitze/",
    topoImg: "https://www.bergsteigen.com/fileadmin/_processed_/e/2/csm_bw3_adamplatte_alpspitze_topo_0_287636388a.jpg",
    wallImg: "https://www.geiselstein.com/uploads/8/4/4/0/84402202/2026-07-11-00_orig.jpg",
    map: "https://www.openstreetmap.org/#map=15/47.440/11.050"
  },
  {
    id: "silenzio",
    rank: 7,
    overGrade: false,
    name: "Silenzio",
    wall: "Scheffauer Nordwand",
    massif: "Kaisergebirge",
    day: "sat",
    dayLabel: "Sat · one pitch of 6",
    drive: "1:30–1:45",
    via: "Kaindlhütte",
    aspect: "N",
    grade: "UIAA 6",
    gradeNote: "One pitch 6 (or 5/A0) and one 5−. Mostly 3–4. Fits “only a few pitches at 6.”",
    pitches: "~15 / 520 m",
    protection: "alpine-bolted",
    protectionNote: "Hard bits well bolted; easy terrain sparser. E2.",
    why: "True north, at the grade cap but only briefly. Directer than the Ostler.",
    approach: "Same as Ostler. Entry ~50 m left, steep crack-corner, left of nettles.",
    descent: "Widauersteig ~1 h.",
    gear: ["50 m rope", "Draws + nuts and slings", "Helmet"],
    weekend: "Saturday. A0 the crux if you want to stay under 6.",
    dont: ["On-sight the 6 as the first pitch of a 15-pitch north face if it is your limit", "Sunday"],
    neighbor: "Ostlerführe avoids the 6 entirely.",
    topoPage: "https://www.stadler-markus.de/alpinklettern/wilder-kaiser/kletterroute/silenzio.html",
    topoImg: "",
    wallImg: "https://www.stadler-markus.de/typo3temp/assets/_processed_/d/2/csm_ScheffauerSilenzio_071f291c70.jpg",
    map: "https://www.openstreetmap.org/#map=14/47.567/12.183"
  },
  {
    id: "benediktenwand",
    rank: 8,
    overGrade: false,
    name: "Rampen-Rippe",
    wall: "Benediktenwand Nord",
    massif: "Bayerische Voralpen",
    day: "sat",
    dayLabel: "Sat · closest N wall",
    drive: "0:55–1:10",
    via: "A95 / Jachenau",
    aspect: "N",
    grade: "UIAA 4+",
    gradeNote: "Mostly easier alpine. Direct rib has 6–7 bits — stay on the original 4+.",
    pitches: "~13–14 / 400–470 m",
    protection: "alpine",
    protectionNote: "Mixed bolts / pins / terrain. Not a sport grid.",
    why: "Closest serious north wall. Shade. Grade fits if you skip the direct rib.",
    approach: "Tutzinger Hütte, entry almost behind the hut. Bike from Jachenau.",
    descent: "Alpine walk-off.",
    gear: ["60 m rope", "8–10 draws", "Slings, basic nuts/friends", "Helmet"],
    weekend: "Saturday or short-drive fallback. Lower than Alpspitze — still warm.",
    dont: ["Climb the direct rib (6–7)", "Expect Osterfelder-cool air"],
    neighbor: "Maximiliansweg is the 3− easy classic next door.",
    topoPage: "https://www.bergsteigen.com/touren/klettern/rampen-rippe-benediktenwand/",
    topoImg: "https://www.bergsteigen.com/fileadmin/_processed_/9/0/csm_rampen_rippe_topo_benediktenwand_d9f4246b5f.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.697/11.417"
  },
  {
    id: "kampenwand",
    rank: 9,
    overGrade: false,
    name: "Nordwand (Zeller)",
    wall: "Kampenwand Nordgipfel",
    massif: "Chiemgauer Alpen",
    day: "sun",
    dayLabel: "Sun default · short",
    drive: "1:15–1:30",
    via: "Kampenwandbahn",
    aspect: "N",
    grade: "UIAA 5−",
    gradeNote: "Two pitches, 4+ / 5−.",
    pitches: "2 / 75 m",
    protection: "alpine",
    protectionNote: "Pins + bolts. E3. No extra gear required.",
    why: "True north, short, Sunday-east. Done before storms.",
    approach: "Bahn to Bergstation, under the Kaisersäle left to the north entries.",
    descent: "One 30 m rap into the Kaisersäle. No loose rock onto people.",
    gear: ["60 m rope", "Draws", "Helmet"],
    weekend: "Sunday morning. Down by 13:00.",
    dont: ["Wander onto the Südwände", "Call the Überschreitung well-protected sport"],
    neighbor: "Mechanikerkante is the 5+ neighbor.",
    topoPage: "https://sebastian-steude.de/klettern/routen/kampenwand-nordgipfel-nordwand/",
    topoImg: "https://sebastian-steude.de/_astro/topo.9SHnnyj-_Z1HOvm.webp",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.757/12.367"
  },
  {
    id: "hoellentorkopf",
    rank: 10,
    overGrade: false,
    name: "Nordkante",
    wall: "Höllentorkopf",
    massif: "Wetterstein",
    day: "sat",
    dayLabel: "Sat Plan B",
    drive: "1:20–1:35",
    via: "Same Bahn as Alpspitze",
    aspect: "N",
    grade: "UIAA 4+",
    gradeNote: "Place 5−. 14 pitches. Route-finding errors are common.",
    pitches: "14 / ~480 m",
    protection: "alpine",
    protectionNote: "Most stands bolted. Not bolts every 2 m.",
    why: "Same logistics as Alpspitze. Moderate alpine ridge.",
    approach: "Alpspitzbahn → Hupfleitenjoch / Knappenhäuser, then left through pines. Budget real approach time.",
    descent: "Höllentor → Osterfelder. Last Bahn 17:30.",
    gear: ["60 m rope", "Draws, slings, basic friends", "Helmet", "Headlamp if slow"],
    weekend: "Saturday. Not a Sunday storm-day route.",
    dont: ["Call it plaisir", "Underestimate upper schrofen"],
    neighbor: "Take the Deichjodler 2025 topo.",
    topoPage: "https://www.deichjodler.com/2020/09/hoellentorkopf-nordkante/",
    topoImg: "https://www.deichjodler.com/wp-content/uploads/2025/12/Wetterstein_HoellentorkopfNordkante_v3-scaled.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.435/11.045"
  },
  {
    id: "kg-weg",
    rank: 11,
    overGrade: false,
    name: "KG-Weg",
    wall: "Alpspitze Nord / NO",
    massif: "Wetterstein",
    day: "sat",
    dayLabel: "Sat · alpine 4+",
    drive: "1:20–1:35",
    via: "Alpspitzbahn",
    aspect: "N / NE",
    grade: "UIAA 4+",
    gradeNote: "Few places 4+; mostly 3–4. More alpine than BW3.",
    pitches: "several",
    protection: "alpine",
    protectionNote: "Mixed bolts — not as tight as BW3.",
    why: "Same high face, grade fits. Pick BW3 if you want more bolts.",
    approach: "Osterfelderkopf, Nordwandsteig, near BW3 / left of Alpspitz-Plaisir.",
    descent: "Ferrata or Ostgrat + Nordwandsteig.",
    gear: ["60 m rope", "Draws + slings", "Small rack", "Helmet"],
    weekend: "Saturday. Do not continue into runout Adamplatte.",
    dont: ["Confuse with Alpspitz-Plaisir (over grade)", "Miss the last Bahn"],
    neighbor: "BW3 is the bolt-friendlier sockel.",
    topoPage: "https://www.segeln-und-klettern.de/klettern/alpspitze-kg-weg/",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.440/11.050"
  },
  {
    id: "rebitschkante",
    rank: 12,
    overGrade: false,
    name: "Rebitschkante",
    wall: "Rotspitz Ostwand",
    massif: "Rofan / Achensee",
    day: "sat",
    dayLabel: "Sat early · east",
    drive: "1:30–1:50",
    via: "Rofanbahn",
    aspect: "E",
    grade: "5b / 4c obl.",
    gradeNote: "Two pitches: 5b then 4c.",
    pitches: "2 / 70 m",
    protection: "mixed",
    protectionNote: "Sanierte classic.",
    why: "High, short, moderate. Not north. Pair with Hosentöter if you want shade after.",
    approach: "Rofanbahn → Rotspitz ~45 min.",
    descent: "Normal route from the summit.",
    gear: ["60 m double", "10 draws", "Helmet"],
    weekend: "Only very early Saturday.",
    dont: ["Start at noon", "Confuse with Rotspitz Süd"],
    neighbor: "Hosentöter is the north-face pick on the same peak.",
    topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/rotspitz/",
    topoImg: "https://www.climbers-paradise.com/uploads/climbers_paradise/images/resources/93112864/achensee_msl_rotspitz_ostwand_75dpi.jpg",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=14/47.452/11.763"
  },
  {
    id: "gnadenlosen-drei",
    rank: 13,
    overGrade: false,
    name: "Die Gnadenlosen Drei",
    wall: "Hörndlwand",
    massif: "Chiemgauer Alpen",
    day: "sun",
    dayLabel: "Sun east",
    drive: "1:30–1:45",
    via: "A8 / Ruhpolding / Seehaus",
    aspect: "NE / N",
    grade: "UIAA 5",
    gradeNote: "8 pitches at 5. Gelbe Wand on the same mountain is 7− — over grade.",
    pitches: "8 / ~200 m",
    protection: "alpine-bolted",
    protectionNote: "Neighbor lines were retro-bolted; verify this one live.",
    why: "Chiemgau Sunday-east. Grade 5. Longer moderate Hörndl line.",
    approach: "Seehaus → Hörndlalm / sockel, 1.5–2 h / 750 Hm.",
    descent: "Ridge west to main summit, then Hörndlalm.",
    gear: ["50–60 m rope", "10 draws", "Slings", "Helmet"],
    weekend: "Sunday morning. Take Panico Bayerische Alpen 1.",
    dont: ["Climb Gelbe Wand / No Fear Anderl / Spaceballs"],
    neighbor: "Neuer Schmidkunzweg is the easy 3+ on the same peak.",
    topoPage: "https://www.stadler-markus.de/klettern/hoerndlwand.html",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=14/47.711/12.622"
  },
  {
    id: "schmidkunzweg",
    rank: 14,
    overGrade: false,
    name: "Neuer Schmidkunzweg",
    wall: "Hörndlwand",
    massif: "Chiemgauer Alpen",
    day: "sun",
    dayLabel: "Sun · easy alpine",
    drive: "1:30–1:45",
    via: "Seehaus",
    aspect: "N / NE",
    grade: "UIAA 3+",
    gradeNote: "Easy alpine mountain route, not sport multi-pitch.",
    pitches: "short pitches + walking",
    protection: "alpine",
    protectionNote: "Classic mountain route, not a bolt grid.",
    why: "Easy, east of Munich, north-facing start. Good if 5+ still feels like a lot.",
    approach: "Seehaus → Hörndlalm / sockel, 1.5–2 h.",
    descent: "Hörndlalm path or the same way.",
    gear: ["50 m rope", "Few draws", "Slings", "Helmet"],
    weekend: "Sunday backup to be off early.",
    dont: ["Expect bolts every 2 m", "Confuse with Gelbe Wand"],
    neighbor: "Gnadenlosen Drei is the 5 / 8-pitch line.",
    topoPage: "https://www.alpenvereinaktiv.com/de/tour/neuer-schmidkunzweg-iii-auf-die-hoerndlwand-1684-m-/808280149/",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=14/47.711/12.622"
  },
  {
    id: "maximiliansweg",
    rank: 15,
    overGrade: false,
    name: "Maximiliansweg",
    wall: "Benediktenwand Nord",
    massif: "Bayerische Voralpen",
    day: "sat",
    dayLabel: "Sat · very easy N",
    drive: "0:55–1:10",
    via: "Jachenau / Tutzinger Hütte",
    aspect: "N",
    grade: "UIAA 3−",
    gradeNote: "The easy classic next to Rampe-Rippe.",
    pitches: "long easy alpine",
    protection: "alpine",
    protectionNote: "Sparse. Not well-protected sport.",
    why: "Closest north wall, lowest grade. Only if you want a gentle alpine day.",
    approach: "Tutzinger Hütte, minutes to the entries.",
    descent: "Normal routes / hut.",
    gear: ["Rope", "Few slings", "Helmet"],
    weekend: "Only if the party wants easy north terrain.",
    dont: ["Call it well-protected sport", "Underestimate grass / route-finding"],
    neighbor: "Rampen-Rippe if 4+ is OK.",
    topoPage: "https://www.thecrag.com/en/climbing/germany/area/3739172820",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.697/11.417"
  },
  {
    id: "mechanikerkante",
    rank: 16,
    overGrade: false,
    name: "Mechanikerkante",
    wall: "Kampenwand Nordgipfel",
    massif: "Chiemgauer Alpen",
    day: "sun",
    dayLabel: "Sun short · 5+",
    drive: "1:15–1:30",
    via: "Kampenwandbahn",
    aspect: "N",
    grade: "UIAA 5+",
    gradeNote: "Two pitches / ~70 m. Still under 6.",
    pitches: "2 / 70 m",
    protection: "alpine",
    protectionNote: "Bolts and fixed threads.",
    why: "True north, short, Sunday-east. A step up from the Zeller Nordwand.",
    approach: "Bahn or Steinlingalm, left under the Kaisersäle.",
    descent: "Rap toward Kaisersäle.",
    gear: ["60 m rope", "Draws", "Helmet"],
    weekend: "Sunday morning.",
    dont: ["Wander onto the south faces"],
    neighbor: "Zeller Nordwand is the easier 5−.",
    topoPage: "https://sebastian-steude.de/klettern/routen/kampenwand-nordgipfel-nordwand/",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=15/47.757/12.367"
  },
  {
    id: "sparchen",
    rank: 17,
    overGrade: "partial",
    name: "Sparchen garden",
    wall: "Schanzer Wände",
    massif: "Zahmer Kaiser / Inntal",
    day: "sun",
    dayLabel: "Sun AM · garden only",
    drive: "1:10–1:25",
    via: "A8 + A93 → Kufstein",
    aspect: "NW",
    grade: "5–6",
    gradeNote: "Use easier MSL / sport. Möwe Jonathan is 7+ — over grade.",
    pitches: "1–several",
    protection: "plaisir",
    protectionNote: "Fully bolted. Shade until ~14:00.",
    why: "Best Sunday logistics. Stay in the garden. Do not force Jonathan.",
    approach: "Kaisertalstraße barrier. 2–5 min to Sector A.",
    descent: "Rappel. 60 m free-hanging option exists.",
    gear: ["60 m double or 50 m single", "14 draws", "Helmet"],
    weekend: "Sunday morning. Off by 13:00.",
    dont: ["Climb Möwe Jonathan (7+)", "Drop stones on Sector B"],
    neighbor: "Alt start 5+ exists if you only want the first pitch of Jonathan.",
    topoPage: "https://www.stadler-markus.de/alpinklettern/wilder-kaiser/kletterroute/moewe-jonathan.html",
    topoImg: "https://www.stadler-markus.de/typo3temp/assets/_processed_/b/4/csm_fal-tempfile-5150500729546342401_9293472524.png",
    wallImg: "https://www.stadler-markus.de/typo3temp/assets/_processed_/0/6/csm_SchanzerWaendeMoeweJonathan_caa392f602.jpg",
    map: "https://www.openstreetmap.org/#map=16/47.592/12.185"
  },
  {
    id: "zahmer-kaiser",
    rank: 18,
    overGrade: false,
    name: "Kufstein MSL cluster",
    wall: "Zahmer Kaiser",
    massif: "Kaisergebirge + Inntal",
    day: "sun",
    dayLabel: "Sun east filler",
    drive: "1:20–1:35",
    via: "Kaisertal",
    aspect: "mixed",
    grade: "5–6",
    gradeNote: "Confirm the wall is N/NW and max 6 the night before.",
    pitches: "various",
    protection: "mixed",
    protectionNote: "No single “the” north plaisir. Prefer Sparchen garden or Scheffauer.",
    why: "East-side options if the named walls are slammed.",
    approach: "Depends on the wall.",
    descent: "Per topo.",
    gear: ["60 m rope", "12 draws", "Helmet"],
    weekend: "Prefer a named north line instead.",
    dont: ["Pick a wall without checking aspect and max grade"],
    neighbor: "Multerkarwand has Climbers Paradise topos.",
    topoPage: "https://www.climbers-paradise.com/kletterregionen/kufsteinerland/mehrseillaengen/",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=13/47.595/12.210"
  },
  {
    id: "zettenkaiser-ost",
    rank: 19,
    overGrade: false,
    name: "Zettenkaiser Ostwand",
    wall: "Zettenkaiser",
    massif: "Kaisergebirge",
    day: "sat",
    dayLabel: "Sat early · thin card",
    drive: "1:30–1:45",
    via: "Kaindlhütte",
    aspect: "E",
    grade: "UIAA 4",
    gradeNote: "Classic neighbor of the Scheffauer. Confirm live.",
    pitches: "multi-pitch alpine",
    protection: "alpine",
    protectionNote: "Thinner research — take a real topo.",
    why: "Same hut as Ostler / Nordwandliebe. Grade 4. East = morning sun.",
    approach: "Kaindlhütte toward the Zettenkaiser (west of Scheffauer).",
    descent: "Per topo / hut paths.",
    gear: ["50–60 m rope", "Draws, slings, small rack", "Helmet"],
    weekend: "Not the first pick. Prefer the true north face.",
    dont: ["Start in midday heat", "Go without a guidebook topo"],
    neighbor: "Ostlerführe and Nordwandliebe are the better-documented north lines.",
    topoPage: "https://www.bergsteigen.com/touren/klettern/ostler-fuehre-scheffauer/",
    topoImg: "",
    wallImg: "",
    map: "https://www.openstreetmap.org/#map=14/47.567/12.183"
  },
  {
    id: "tirol-plaisir",
    rank: 20,
    overGrade: true,
    name: "Tirol Plaisir",
    wall: "Seebenwände",
    massif: "Mieminger / Zugspitz Arena",
    day: "sat",
    dayLabel: "Over grade",
    drive: "1:35–1:50",
    via: "A95 + B23 → Ehrwald",
    aspect: "N",
    grade: "UIAA 6+",
    gradeNote: "Crux pitches 3–4 are 6+. Over the new cap.",
    pitches: "6 / ~150–200 m",
    protection: "plaisir",
    protectionNote: "Modern bolts, rappel-ready stands. The protection is perfect; the grade is not.",
    why: "Still the best north plaisir wall — but the easiest line is 6+. Listed last under the new lock.",
    approach: "Ehrwalder Alm → Seeben waterfall, 30–40 min.",
    descent: "Rappel the route.",
    gear: ["60 m double / twin", "12 draws", "Helmet"],
    weekend: "Skip unless the cap is lifted.",
    dont: ["Default to this after the 6+ lock"],
    neighbor: "There is no easier Seebenwände line.",
    topoPage: "https://www.bergprofi.com/versteckte-unterseiten/topos/tirol-plaisier/",
    topoImg: "https://image.jimcdn.com/app/cms/image/transf/dimension=304x1024:format=jpg/path/s1a2fe1b546fb36cd/image/i103fe1c0e3614b53/version/1461498705/image.jpg",
    wallImg: "https://image.jimcdn.com/app/cms/image/transf/dimension=755x10000:format=jpg/path/s1a2fe1b546fb36cd/image/if3a779e7fa116977/version/1461497791/image.jpg",
    map: "https://www.openstreetmap.org/#map=16/47.421/10.956"
  }
];
