/* Routes 31–100. Compact public-source cards from the Tölz catchment.
   Scored at runtime. Not a guidebook. */
(function () {
  const BENE = "assets/topos/rampen-rippe-overview.jpg";
  const BENE_M = "assets/topos/rampen-rippe-overview.jpg";
  const LEBE = "assets/topos/lebe-deinen-traum-wall.jpg";
  const ALP = "assets/topos/alpspitze-overview.jpg";
  const ALP_M = "assets/topos/alpspitze-overview.jpg";
  const BUCH_S = "assets/topos/buchstein-south-overview.jpg";
  const ROF = "assets/topos/rotspitz.jpg";
  const ROF_M = "assets/media/897d6bd95769.jpg";
  const KAM = "assets/topos/kampenwand.jpg";
  const KAM_M = "assets/media/be9b23a777cd.webp";
  const KAI = "assets/topos/nordwandliebe.png";
  const KAI_M = "assets/media/dbd960058724.jpg";
  const SPA = "assets/media/151acbe92553.jpg";
  const GEI = "assets/media/6a69a05f82d8.jpg";

  function pack(r) {
    return r;
  }

  const extra = [
    pack({
      id: "vronerl",
      rank: 31,
      name: "Vronerl",
      wall: "Buchstein Nordwestwand",
      massif: "Bayerische Voralpen / Tegernsee",
      day: "sun",
      dayLabel: "Sun · practice 5−",
      drive: "0:35–0:50",
      via: "B13 / Kreuth / Tegernseer Hütte",
      aspect: "NW",
      grade: "UIAA 5−",
      gradeNote: "Hut course line under the terrace. One step up from Simplinella.",
      pitches: "1–2 / short",
      protection: "alpine-bolted",
      protectionNote: "Used for courses. Alpine spacing.",
      why: "Sunday-close, north-west, moderate. Good if Nordkante 5 is a stretch.",
      approach: "Tegernseer Hütte, NW wall, minutes from the terrace.",
      descent: "Walk to the hut / normal route.",
      gear: ["60 m rope", "8 draws", "Helmet"],
      weekend: "Sunday morning warm-up.",
      dont: ["Wander onto Herr der Fliegen (7)"],
      neighbor: "Simplinella is the 4. Nordkante is the real 3-pitch 5.",
      topoPage: "https://tegernseerhuette.de/bewegen",
      topoImg: "",
      map: "https://www.openstreetmap.org/#map=16/47.626/11.801",
      lat: 47.6263,
      lng: 11.8008,
      photos: [],
      de: {
        dayLabel: "So · Übung 5−",
        via: "B13 / Kreuth / Tegernseer Hütte",
        why: "Sonntag nah, Nordwest, moderat. Gut, wenn Nordkante 5 beißt.",
        gradeNote: "Hütten-Kurslinie unter der Terrasse. Eine Stufe über Simplinella.",
        protectionNote: "Für Kurse. Alpine Abstände.",
        approach: "Tegernseer Hütte, Nordwestwand, Minuten von der Terrasse.",
        descent: "Zur Hütte / Normalweg.",
        weekend: "Sonntag vormittag zum Warmwerden.",
        dont: ["Nicht auf Herr der Fliegen (7) geraten"],
        neighbor: "Simplinella ist die 4. Nordkante ist die echte 3-SL-5.",
        gear: ["60-m-Seil", "8 Exen", "Helm"]
      }
    }),
    pack({
      id: "huehnerleiter",
      rank: 32,
      name: "Hühnerleiter",
      wall: "Buchstein Nordwestwand",
      massif: "Bayerische Voralpen / Tegernsee",
      day: "sun",
      dayLabel: "Sun · 5+ under the hut",
      drive: "0:35–0:50",
      via: "B13 / Kreuth / Tegernseer Hütte",
      aspect: "NW",
      grade: "UIAA 5+",
      gradeNote: "Almost 50 m, alpine bolt spacing. Hut page: do not rappel — you exit near the normal route.",
      pitches: "1 / ~50 m",
      protection: "alpine-bolted",
      protectionNote: "Long single pitch. Alpine gaps.",
      why: "True local shade wall, one hard-ish pitch, 35 minutes.",
      approach: "Directly under the hut on the NW wall.",
      descent: "Walk the Buchstein normal route. Rap does not make sense.",
      gear: ["60 m rope", "12 draws", "Helmet"],
      weekend: "Sunday if you want one proper 5+ and coffee after.",
      dont: ["Rappel this line", "Treat 50 m as a gym pitch"],
      neighbor: "Vronerl is the easier 5−.",
      topoPage: "https://tegernseerhuette.de/bewegen",
      topoImg: "",
      map: "https://www.openstreetmap.org/#map=16/47.626/11.801",
      lat: 47.6265,
      lng: 11.801,
      photos: [],
      de: {
        dayLabel: "So · 5+ unter der Hütte",
        via: "B13 / Kreuth / Tegernseer Hütte",
        why: "Lokale Schattenwand, eine knackige Länge, 35 Minuten.",
        gradeNote: "Fast 50 m, alpine Hakenabstände. Nicht abseilen — Ausstieg am Normalweg.",
        protectionNote: "Lange Einzellänge. Alpine Lücken.",
        approach: "Direkt unter der Hütte an der Nordwestwand.",
        descent: "Buchstein-Normalweg. Abseilen lohnt nicht.",
        weekend: "Sonntag, eine echte 5+ und Kaffee danach.",
        dont: ["Nicht abseilen", "50 m sind hier keine Hallenlänge"],
        neighbor: "Vronerl ist die leichtere 5−.",
        gear: ["60-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "westpfeiler-ross",
      rank: 33,
      name: "Westpfeiler",
      wall: "Roßstein Südwest",
      massif: "Bayerische Voralpen / Tegernsee",
      day: "sun",
      dayLabel: "Sun · 3-pitch 4−",
      drive: "0:35–0:50",
      via: "B13 / Kreuth / Tegernseer Hütte",
      aspect: "SW",
      grade: "UIAA 4−",
      gradeNote: "Three easy pitches, good stands. Hut course closer. SW — early only on a heat day.",
      pitches: "3 / easy",
      protection: "alpine-bolted",
      protectionNote: "Course-friendly stands.",
      why: "Closest 3-pitch practice line. Wrong aspect for midday heat.",
      approach: "Roßstein SW side, minutes from the hut.",
      descent: "Walk / hut.",
      gear: ["60 m rope", "8 draws", "Helmet"],
      weekend: "Sunday 7:30 start or skip if you need shade.",
      dont: ["Start after 09:30 in a heat wave"],
      neighbor: "Zwergerlrutschbahn is the 3+ on the Sonnenplatten.",
      topoPage: "https://tegernseerhuette.de/bewegen",
      topoImg: "",
      map: "https://www.openstreetmap.org/#map=16/47.625/11.798",
      lat: 47.6254,
      lng: 11.7984,
      photos: [],
      de: {
        dayLabel: "So · 3 SL 4−",
        via: "B13 / Kreuth / Tegernseer Hütte",
        why: "Nächste 3-SL-Übung. Falsche Seite für Mittagshitze.",
        gradeNote: "Drei leichte Längen, gute Stände. SW — bei Hitze nur früh.",
        protectionNote: "Kurs-taugliche Stände.",
        approach: "Roßstein-Südwest, Minuten von der Hütte.",
        descent: "Zu Fuß / Hütte.",
        weekend: "Sonntag 7:30 oder lassen, wenn Schatten muss.",
        dont: ["Nicht nach 9:30 bei Hitze"],
        neighbor: "Zwergerlrutschbahn ist die 3+ an den Sonnenplatten.",
        gear: ["60-m-Seil", "8 Exen", "Helm"]
      }
    }),
    pack({
      id: "zwergerlrutschbahn",
      rank: 34,
      name: "Zwergerlrutschbahn",
      wall: "Roßstein Sonnenplatten",
      massif: "Bayerische Voralpen / Tegernsee",
      day: "sun",
      dayLabel: "Sun · easy 3+",
      drive: "0:35–0:50",
      via: "B13 / Kreuth / Tegernseer Hütte",
      aspect: "S",
      grade: "UIAA 3+",
      gradeNote: "Sonnenplatten course pitch. South — heat reject as an A-plan.",
      pitches: "2 / short",
      protection: "alpine-bolted",
      protectionNote: "Course bolts.",
      why: "Only if you want an easy closer after a north pitch. South oven.",
      approach: "Sonnenplatten, SW of the needle.",
      descent: "Walk to hut.",
      gear: ["60 m rope", "8 draws", "Helmet"],
      weekend: "Not a heat-weekend A-plan.",
      dont: ["Pick this for shade"],
      neighbor: "Westgrat on the needle is the famous 3.",
      topoPage: "https://tegernseerhuette.de/bewegen",
      topoImg: "",
      map: "https://www.openstreetmap.org/#map=16/47.625/11.798",
      lat: 47.6252,
      lng: 11.798,
      photos: [],
      de: {
        dayLabel: "So · leicht 3+",
        via: "B13 / Kreuth / Tegernseer Hütte",
        why: "Nur als leichter Abschluss nach einer Nordlänge. Süd-Ofen.",
        gradeNote: "Sonnenplatten-Kurs. Süd — bei Hitze kein A-Plan.",
        protectionNote: "Kurs-Haken.",
        approach: "Sonnenplatten, südwestlich der Nadel.",
        descent: "Zur Hütte.",
        weekend: "Kein Hitze-A-Plan.",
        dont: ["Nicht für Schatten wählen"],
        neighbor: "Westgrat der Nadel ist die berühmte 3.",
        gear: ["60-m-Seil", "8 Exen", "Helm"]
      }
    }),
    pack({
      id: "suedwand-schmankerl",
      rank: 35,
      name: "Südwandschmankerl",
      wall: "Buchstein Südwand",
      massif: "Bayerische Voralpen / Tegernsee",
      day: "sat",
      dayLabel: "Sat · south 6−",
      drive: "0:35–0:50",
      via: "B13 / Kreuth / Tegernseer Hütte",
      aspect: "S",
      grade: "UIAA 6−",
      gradeNote: "5 pitches, 6− obligatory. Famous. Wrong aspect for heat.",
      pitches: "5 / ~150 m",
      protection: "alpine-bolted",
      protectionNote: "Modern bolts on the classic dihedral. Not a gym grid.",
      why: "Best south line at the hut. Heat reject. Listed so the pool is honest.",
      approach: "Path along Roßstein then Buchstein south, metal name plate in the dihedral.",
      descent: "Normalweg chimney (II, polished) to the hut.",
      gear: ["60 m rope", "10 draws", "Slings", "Helmet"],
      weekend: "Skip this heat weekend.",
      dont: ["Pick this for shade", "Start late"],
      neighbor: "Zauberrippe around the corner is the north 6.",
      topoPage: "https://www.bergsteigen.com/touren/klettern/suedwand-schmankerl-buchstein/",
      topoImg: BUCH_S,
      map: "https://www.openstreetmap.org/#map=16/47.625/11.802",
      lat: 47.6256,
      lng: 11.8018,
      photos: [BUCH_S],
      de: {
        dayLabel: "Sa · Süd 6−",
        via: "B13 / Kreuth / Tegernseer Hütte",
        why: "Beste Südlinie an der Hütte. Bei Hitze tabu. Steht in der Liste, damit der Pool ehrlich ist.",
        gradeNote: "5 SL, 6− obl. Berühmt. Falsche Seite für Hitze.",
        protectionNote: "Moderne Haken in der Klassiker-Verschneidung.",
        approach: "Pfad an Roß- und Buchstein-Süd, Metallschild in der Verschneidung.",
        descent: "Normalweg-Rinne (II, speckig) zur Hütte.",
        weekend: "Dieses Hitzewochenende lassen.",
        dont: ["Nicht für Schatten", "Nicht spät starten"],
        neighbor: "Zauberrippe um die Ecke ist die Nord-6.",
        gear: ["60-m-Seil", "10 Exen", "Schlingen", "Helm"]
      }
    }),
    pack({
      id: "ostpfeiler-bene",
      rank: 36,
      name: "Ostpfeiler",
      wall: "Benediktenwand Ostpfeiler",
      massif: "Bayerische Voralpen",
      day: "sat",
      dayLabel: "Sat · east pillar",
      drive: "0:20–0:35",
      via: "B472 / Tutzinger Hütte",
      aspect: "E",
      grade: "UIAA 4",
      gradeNote: "East pillar sector, up to ~110 m. Morning sun. theCrag lists mixed trad/sport.",
      pitches: "several / ~110 m",
      protection: "alpine",
      protectionNote: "Mixed. Take Panico Band 3.",
      why: "Same 25-minute wall, quieter than Rampe-Rippe, east so go early.",
      approach: "Tutzinger Hütte, 30–45 min toward the east pillar.",
      descent: "Walk-off / hut.",
      gear: ["60 m rope", "Draws", "Nuts/slings", "Helmet"],
      weekend: "Saturday early. Not all-day shade.",
      dont: ["Treat east as north", "Go without a real topo"],
      neighbor: "Rampen-Rippe is the central north classic.",
      topoPage: "https://www.thecrag.com/en/climbing/germany/area/4024401897",
      topoImg: BENE,
      map: "https://www.openstreetmap.org/#map=15/47.654/11.47",
      lat: 47.654,
      lng: 11.4705,
      photos: [BENE_M],
      de: {
        dayLabel: "Sa · Ostpfeiler",
        via: "B472 / Tutzinger Hütte",
        why: "Dieselbe 25-Minuten-Wand, ruhiger als Rampe-Rippe, Ost — früh.",
        gradeNote: "Ostpfeiler, bis ~110 m. Morgensonne. Gemischt trad/sport.",
        protectionNote: "Gemischt. Panico Band 3.",
        approach: "Tutzinger Hütte, 30–45 Min. zum Ostpfeiler.",
        descent: "Zu Fuß / Hütte.",
        weekend: "Samstag früh. Kein Ganztagsschatten.",
        dont: ["Ost nicht als Nord", "Nicht ohne echtes Topo"],
        neighbor: "Rampen-Rippe ist der zentrale Nord-Klassiker.",
        gear: ["60-m-Seil", "Exen", "Keile/Schlingen", "Helm"]
      }
    }),
    pack({
      id: "kamine-steilschlucht",
      rank: 37,
      name: "Kamine der Steilschlucht",
      wall: "Benediktenwand Nord",
      massif: "Bayerische Voralpen",
      day: "sat",
      dayLabel: "Sat · chimneys 3",
      drive: "0:20–0:35",
      via: "B472 / Tutzinger Hütte",
      aspect: "N",
      grade: "UIAA 3",
      gradeNote: "200 m trad chimneys. theCrag, Rampe-Rippe sector.",
      pitches: "~200 m",
      protection: "alpine",
      protectionNote: "Old alpine. Sparse.",
      why: "Another Tölz-doorstep 3 on the true north face.",
      approach: "Tutzinger Hütte, Rampe sector.",
      descent: "Walk-off / hut.",
      gear: ["Rope", "Slings, nuts", "Helmet"],
      weekend: "Saturday easy-north filler.",
      dont: ["Expect bolts"],
      neighbor: "Höhlenweg and Winklerführe share the sector.",
      topoPage: "https://www.thecrag.com/en/climbing/germany/route/4024450512",
      topoImg: BENE,
      map: "https://www.openstreetmap.org/#map=15/47.654/11.462",
      lat: 47.6542,
      lng: 11.4618,
      photos: [BENE_M],
      de: {
        dayLabel: "Sa · Kamine 3",
        via: "B472 / Tutzinger Hütte",
        why: "Noch eine Tölzer 3 an der echten Nordwand.",
        gradeNote: "200 m Trad-Kamine. Rampe-Sektor.",
        protectionNote: "Altes Alpin. Lückig.",
        approach: "Tutzinger Hütte, Rampe-Sektor.",
        descent: "Zu Fuß / Hütte.",
        weekend: "Samstag, leichte Nord-Lücke.",
        dont: ["Keine Haken erwarten"],
        neighbor: "Höhlenweg und Winklerführe im selben Sektor.",
        gear: ["Seil", "Schlingen, Keile", "Helm"]
      }
    }),
    pack({
      id: "rotoehrlpfeiler",
      rank: 38,
      name: "Rotöhrlpfeiler",
      wall: "Benediktenwand Rotöhrl",
      massif: "Bayerische Voralpen",
      day: "sat",
      dayLabel: "Sat · far left N",
      drive: "0:20–0:35",
      via: "B472 / Tutzinger Hütte",
      aspect: "N",
      grade: "UIAA 4",
      gradeNote: "Left end of the north wall. ~110 m. 45 min from the hut. Quiet.",
      pitches: "~110 m",
      protection: "alpine",
      protectionNote: "Trad / alpine. Panico Band 3.",
      why: "Same north wall, furthest walk, fewest parties.",
      approach: "Tutzinger Hütte, 45 min left to Rotöhrlpfeiler.",
      descent: "Walk-off.",
      gear: ["60 m rope", "Slings, nuts", "Helmet"],
      weekend: "Saturday if Rampe-Rippe is a zoo.",
      dont: ["Underestimate the extra approach"],
      neighbor: "Linke Nordwand / Meiser-Wülfert is closer.",
      topoPage: "https://www.thecrag.com/en/climbing/germany/area/4024401813",
      topoImg: BENE,
      map: "https://www.openstreetmap.org/#map=15/47.655/11.458",
      lat: 47.6552,
      lng: 11.4584,
      photos: [BENE_M],
      de: {
        dayLabel: "Sa · ganz links Nord",
        via: "B472 / Tutzinger Hütte",
        why: "Dieselbe Nordwand, längster Zustieg, wenig Betrieb.",
        gradeNote: "Linkes Ende, ~110 m. 45 Min. ab Hütte.",
        protectionNote: "Trad / alpin. Panico Band 3.",
        approach: "Tutzinger Hütte, 45 Min. links zum Rotöhrlpfeiler.",
        descent: "Zu Fuß.",
        weekend: "Samstag, wenn Rampe-Rippe voll ist.",
        dont: ["Längeren Zustieg nicht unterschätzen"],
        neighbor: "Linke Nordwand / Meiser-Wülfert ist näher.",
        gear: ["60-m-Seil", "Schlingen, Keile", "Helm"]
      }
    }),
    pack({
      id: "adamplatte",
      rank: 39,
      name: "Adamplatte",
      wall: "Alpspitze NO",
      massif: "Wetterstein",
      day: "sat",
      dayLabel: "Sat · high alpine 3–4",
      drive: "0:55–1:15",
      via: "B13 / Walchensee / Alpspitzbahn",
      aspect: "NE",
      grade: "UIAA 3–4",
      gradeNote: "Classic alpine slab. Runout. Not sport. Neighbor of BW3.",
      pitches: "several + terrain",
      protection: "alpine",
      protectionNote: "Not a bolt grid. Route-finding.",
      why: "High and cooler. Only if the party likes alpine runout at 3–4.",
      approach: "Osterfelderkopf, Nordwandsteig.",
      descent: "Ostgrat + Nordwandsteig. Last Bahn 17:30.",
      gear: ["60 m rope", "Slings, small rack", "Helmet"],
      weekend: "Saturday. Do not confuse with BW3.",
      dont: ["Call it well-protected sport", "Miss the Bahn"],
      neighbor: "BW3 is the bolt-friendlier sockel.",
      topoPage: "https://www.bergsteigen.com/touren/klettern/adamplatte-bw3-alpspitze/",
      topoImg: ALP,
      map: "https://www.openstreetmap.org/#map=15/47.425/11.049",
      lat: 47.4246,
      lng: 11.0482,
      photos: [ALP_M],
      de: {
        dayLabel: "Sa · hoch alpin 3–4",
        via: "B13 / Walchensee / Alpspitzbahn",
        why: "Hoch und kühler. Nur wenn die Seilschaft Runout im 3–4. mag.",
        gradeNote: "Klassische alpine Platte. Runout. Kein Sport. Nachbar von BW3.",
        protectionNote: "Kein Bohrhakenraster. Wegfindung.",
        approach: "Osterfelderkopf, Nordwandsteig.",
        descent: "Ostgrat + Nordwandsteig. Letzte Bahn 17:30.",
        weekend: "Samstag. Nicht mit BW3 verwechseln.",
        dont: ["Nicht als gut abgesicherten Sport", "Bahn nicht verpassen"],
        neighbor: "BW3 ist der freundlicher gebohrte Sockel.",
        gear: ["60-m-Seil", "Schlingen, kleine Friends", "Helm"]
      }
    }),
    pack({
      id: "alpspitz-plaisir",
      rank: 40,
      overGrade: true,
      name: "Alpspitz-Plaisir",
      wall: "Alpspitze Nord / NO",
      massif: "Wetterstein",
      day: "sat",
      dayLabel: "Over grade",
      drive: "0:55–1:15",
      via: "B13 / Walchensee / Alpspitzbahn",
      aspect: "N / NE",
      grade: "UIAA 6+",
      gradeNote: "6+ obligatory. Protection is good; the grade is over the lock.",
      pitches: "several",
      protection: "plaisir",
      protectionNote: "Modern bolts. The problem is the grade.",
      why: "Listed so nobody defaults to it after the 6+ lock.",
      approach: "Osterfelderkopf, Nordwandsteig.",
      descent: "Ostgrat / Nordwandsteig.",
      gear: ["60 m rope", "12 draws", "Helmet"],
      weekend: "Skip unless the cap is lifted.",
      dont: ["Default to this"],
      neighbor: "BW3 is the 4 on the sockel.",
      topoPage: "https://www.bergsteigen.com/touren/klettern/adamplatte-bw3-alpspitze/",
      topoImg: ALP,
      map: "https://www.openstreetmap.org/#map=15/47.424/11.049",
      lat: 47.4242,
      lng: 11.049,
      photos: [ALP_M],
      de: {
        dayLabel: "Zu schwer",
        via: "B13 / Walchensee / Alpspitzbahn",
        why: "Steht hier, damit niemand sie trotz der Gradgrenze als erste Wahl nimmt.",
        gradeNote: "6+ obl. Absicherung gut; Grad über der Grenze.",
        protectionNote: "Moderne Haken. Das Problem ist der Grad.",
        approach: "Osterfelderkopf, Nordwandsteig.",
        descent: "Ostgrat / Nordwandsteig.",
        weekend: "Lassen, solange die Grenze gilt.",
        dont: ["Nicht als erste Wahl"],
        neighbor: "BW3 ist die 4 am Sockel.",
        gear: ["60-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "leuchsfuehre",
      rank: 41,
      name: "Leuchsführe",
      wall: "Scheffauer Nordwand",
      massif: "Kaisergebirge",
      day: "sat",
      dayLabel: "Sat · old north 2–3",
      drive: "1:00–1:20",
      via: "B472 / A8 / A93 / Kaindlhütte",
      aspect: "N",
      grade: "UIAA 2–3",
      gradeNote: "Steep grass and schrofen. Almost no bolts. Serious for the grade.",
      pitches: "long alpine",
      protection: "alpine",
      protectionNote: "Two pins in the gully. Slings and nuts.",
      why: "True north, historic, easy climbing. Not well protected.",
      approach: "Kaindlhütte toward Großer Friedhof / Widauersteig.",
      descent: "Widauersteig.",
      gear: ["50 m rope", "Slings", "Nuts", "Helmet"],
      weekend: "Saturday solitude. Do not pick for bolts.",
      dont: ["Treat UIAA 3 as gym 3"],
      neighbor: "Ostlerführe is the bolted 4.",
      topoPage: "https://www.alpenvereinaktiv.com/de/tour/scheffauer-nordwand-leuchsfuehre/102980180/",
      topoImg: KAI,
      map: "https://www.openstreetmap.org/#map=14/47.557/12.176",
      lat: 47.5562,
      lng: 12.1752,
      photos: [KAI_M],
      de: {
        dayLabel: "Sa · alte Nord 2–3",
        via: "B472 / A8 / A93 / Kaindlhütte",
        why: "Echte Nordwand, historisch, leichte Kletterei. Nicht gut abgesichert.",
        gradeNote: "Steile Schrofen. Fast keine Haken. Ernst für den Grad.",
        protectionNote: "Zwei Haken in der Schlucht. Schlingen und Keile.",
        approach: "Kaindlhütte zum Großen Friedhof / Widauersteig.",
        descent: "Widauersteig.",
        weekend: "Samstag für Ruhe. Nicht für Bohrhaken wählen.",
        dont: ["UIAA 3 nicht wie Halle 3"],
        neighbor: "Ostlerführe ist die gebohrte 4.",
        gear: ["50-m-Seil", "Schlingen", "Keile", "Helm"]
      }
    }),
    pack({
      id: "zettenkaiser-ost",
      rank: 42,
      name: "Zettenkaiser Ostwand",
      wall: "Zettenkaiser",
      massif: "Kaisergebirge",
      day: "sat",
      dayLabel: "Sat early · east 4",
      drive: "1:00–1:20",
      via: "B472 / A8 / A93 / Kaindlhütte",
      aspect: "E",
      grade: "UIAA 4",
      gradeNote: "Classic neighbor of the Scheffauer. Confirm live. East = morning sun.",
      pitches: "multi-pitch alpine",
      protection: "alpine",
      protectionNote: "Thinner research — take a real topo.",
      why: "Same hut as Ostler. Grade 4. Not the first pick.",
      approach: "Kaindlhütte toward Zettenkaiser (west of Scheffauer).",
      descent: "Hut paths.",
      gear: ["50–60 m rope", "Draws, slings", "Helmet"],
      weekend: "Prefer the true north face.",
      dont: ["Start at noon", "Go without a guidebook"],
      neighbor: "Nordwandliebe and Ostler are better documented.",
      topoPage: "https://www.bergsteigen.com/touren/klettern/ostler-fuehre-scheffauer/",
      topoImg: KAI,
      map: "https://www.openstreetmap.org/#map=14/47.559/12.165",
      lat: 47.5592,
      lng: 12.1648,
      photos: [KAI_M],
      de: {
        dayLabel: "Sa früh · Ost 4",
        via: "B472 / A8 / A93 / Kaindlhütte",
        why: "Dieselbe Hütte wie Ostler. Grad 4. Nicht die erste Wahl.",
        gradeNote: "Nachbar des Scheffauers. Live prüfen. Ost = Morgensonne.",
        protectionNote: "Dünner recherchiert — echtes Topo.",
        approach: "Kaindlhütte Richtung Zettenkaiser.",
        descent: "Hüttenwege.",
        weekend: "Lieber die echte Nordwand.",
        dont: ["Nicht mittags", "Nicht ohne Führer"],
        neighbor: "Nordwandliebe und Ostler sind besser dokumentiert.",
        gear: ["50–60-m-Seil", "Exen, Schlingen", "Helm"]
      }
    }),
    pack({
      id: "plankenstein-suedwand-reibn",
      rank: 43,
      name: "Südwand Reibn",
      wall: "Plankenstein Südwand",
      massif: "Bayerische Voralpen / Tegernsee",
      day: "sat",
      dayLabel: "Sat · south classic",
      drive: "0:40–0:55",
      via: "Tegernsee / Sutten / Kistenwinterstube",
      aspect: "S",
      grade: "UIAA 5",
      gradeNote: "Bolted multi-pitch south classic. Grass between steps. Heat reject as A-plan.",
      pitches: "several / ~150 m+",
      protection: "alpine-bolted",
      protectionNote: "Bolts on the rock steps; grass in between.",
      why: "Tölz-local south classic. Listed for an honest pool, not for this heat.",
      approach: "Sieblialm → Riedereck saddle → south face.",
      descent: "Same as Ostgrat: slick chimney.",
      gear: ["50–60 m rope", "10 draws", "Helmet"],
      weekend: "Skip if you need shade.",
      dont: ["Pick this for a heat Saturday"],
      neighbor: "Direkter Ostgrat is the public 4+ ridge. North wall is the shade side.",
      topoPage: "https://www.bergsteigen.com/touren/klettern/suedwand-reibn-plankenstein/",
      topoImg: "assets/media/3280077b40fb.jpg",
      map: "https://www.openstreetmap.org/#map=15/47.640/11.803",
      lat: 47.64,
      lng: 11.8032,
      photos: ["assets/media/3280077b40fb.jpg"],
      de: {
        dayLabel: "Sa · Süd-Klassiker",
        via: "Tegernsee / Sutten / Kistenwinterstube",
        why: "Tölzer Süd-Klassiker. In der Liste für einen ehrlichen Pool, nicht für diese Hitze.",
        gradeNote: "Gebohrter Süd-Klassiker. Gras zwischen den Aufschwüngen.",
        protectionNote: "Haken in den Felsstufen; Gras dazwischen.",
        approach: "Sieblialm → Riedereck-Sattel → Südwand.",
        descent: "Wie Ostgrat: glatter Kamin.",
        weekend: "Lassen, wenn Schatten muss.",
        dont: ["Nicht als Hitze-Samstag"],
        neighbor: "Direkter Ostgrat ist der 4+-Grat. Nordwand ist die Schattenseite.",
        gear: ["50–60-m-Seil", "10 Exen", "Helm"]
      }
    }),
    pack({
      id: "plankenstein-hitzefrei",
      rank: 44,
      name: "Hitzefrei sector",
      wall: "Plankenstein Nordwand",
      massif: "Bayerische Voralpen / Tegernsee",
      day: "sat",
      dayLabel: "Sat · N baseclimbs",
      drive: "0:40–0:55",
      via: "Tegernsee / Sutten / Blankensteinalm",
      aspect: "N",
      grade: "UIAA 5–6",
      gradeNote: "Modern north-face baseclimbs, 4+ pitches in the mid grades. Stadler: humanely bolted, stay under 6.",
      pitches: "4+ / north wall",
      protection: "alpine-bolted",
      protectionNote: "Newer north sectors are friendlier than the old south classics.",
      why: "Tölz-local true north, designed for hot days. Take Panico Band 3 and pick a 5.",
      approach: "Bike toward Blankensteinalm, 20–30 min to the north wall.",
      descent: "Rappel the line or walk the north paths.",
      gear: ["60 m rope", "12 draws", "Helmet"],
      weekend: "Saturday shade pick if Benediktenwand is wet.",
      dont: ["Pick a 7 just because it is bolted", "New routes without the Gebietsbetreuer"],
      neighbor: "Direkter Ostgrat is the public ridge. Südwand Reibn is the heat reject.",
      topoPage: "https://www.stadler-markus.de/klettern/plankenstein.html",
      topoImg: "assets/media/3280077b40fb.jpg",
      map: "https://www.openstreetmap.org/#map=15/47.642/11.804",
      lat: 47.6418,
      lng: 11.8042,
      photos: ["assets/media/3280077b40fb.jpg"],
      de: {
        dayLabel: "Sa · Nord-Baseclimbs",
        via: "Tegernsee / Sutten / Blankensteinalm",
        why: "Tölzer echte Nordwand, für heiße Tage. Panico Band 3, eine 5 wählen.",
        gradeNote: "Moderne Nord-Baseclimbs, 4+ SL in mittleren Graden. Humaner gebohrt, unter 6 bleiben.",
        protectionNote: "Neue Nordsektoren freundlicher als alte Südklassiker.",
        approach: "Radl zur Blankensteinalm, 20–30 Min. zur Nordwand.",
        descent: "Abseilen oder Nordwege.",
        weekend: "Samstag Schatten, wenn Benediktenwand nass ist.",
        dont: ["Keine 7 nur weil gebohrt", "Keine Neutour ohne Gebietsbetreuer"],
        neighbor: "Direkter Ostgrat ist der öffentliche Grat. Südwand Reibn ist bei Hitze tabu.",
        gear: ["60-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "gramai-msl",
      rank: 45,
      name: "Gramai MSL",
      wall: "Gramai",
      massif: "Karwendel / Achensee",
      day: "sat",
      dayLabel: "Sat · alpine bolted",
      drive: "0:55–1:15",
      via: "B13 / Achenpass / Pertisau",
      aspect: "N",
      grade: "UIAA 5–6",
      gradeNote: "Climbers Paradise: well bolted but alpine character. Pick a line at or under 6.",
      pitches: "several",
      protection: "alpine-bolted",
      protectionNote: "Rappel with 55 m doubles. Wildlife above — behave.",
      why: "Achenpass-close from Tölz. North-ish alpine sport. Confirm the exact line the night before.",
      approach: "Pertisau / Gramai. Short-ish for Karwendel.",
      descent: "Rappel 55 m doubles.",
      gear: ["55–60 m double", "12 draws", "Helmet"],
      weekend: "Saturday. Confirm aspect of the exact line.",
      dont: ["Pick a 7 because the wall is famous", "Disturb wildlife above"],
      neighbor: "Rotspitz Hosentöter is the named north 5b.",
      topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/gramai/",
      topoImg: ROF,
      map: "https://www.openstreetmap.org/#map=14/47.39/11.59",
      lat: 47.392,
      lng: 11.592,
      photos: [ROF_M],
      de: {
        dayLabel: "Sa · alpin gebohrt",
        via: "B13 / Achenpass / Pertisau",
        why: "Vom Achenpass nah. Alpines Sport, eher Nord. Linie am Vorabend prüfen.",
        gradeNote: "Climbers Paradise: gut gebohrt, alpin. Linie bei max. 6.",
        protectionNote: "Abseilen 55-m-Doppelseil. Wild oben — ruhig bleiben.",
        approach: "Pertisau / Gramai.",
        descent: "55-m-Doppelseil abseilen.",
        weekend: "Samstag. Exposition der genauen Linie prüfen.",
        dont: ["Keine 7 weil die Wand berühmt ist", "Wild nicht stören"],
        neighbor: "Hosentöter an der Rotspitz ist die benannte Nord-5b.",
        gear: ["55–60-m-Doppelseil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "klobenjoch-6",
      rank: 46,
      name: "Klobenjoch moderate",
      wall: "Klobenjoch",
      massif: "Rofan / Achensee",
      day: "sat",
      dayLabel: "Sat · long 6",
      drive: "0:50–1:10",
      via: "B13 / Achenpass / Maurach",
      aspect: "mixed",
      grade: "UIAA 6",
      gradeNote: "Climbers Paradise: long routes in French 6–7. Stay on a 6 / 6a line. Many harder sport lines exist.",
      pitches: "long MSL",
      protection: "alpine-bolted",
      protectionNote: "Good bolts on modern lines. Confirm grade on the plaque.",
      why: "Achenpass-close. Long, well bolted. At the cap — pick carefully.",
      approach: "From the Achensee side toward Klobenjoch.",
      descent: "Rappel or walk per topo.",
      gear: ["60 m rope", "14 draws", "Helmet"],
      weekend: "Saturday. Do not wander into 7s.",
      dont: ["On-sight a 7 because the 6 was busy"],
      neighbor: "Rotspitz is shorter and more moderate.",
      topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/klobenjoch/",
      topoImg: ROF,
      map: "https://www.openstreetmap.org/#map=14/47.45/11.72",
      lat: 47.448,
      lng: 11.722,
      photos: [ROF_M],
      de: {
        dayLabel: "Sa · lange 6",
        via: "B13 / Achenpass / Maurach",
        why: "Achenpass-nah. Lang, gut gebohrt. An der Grenze — Linie sorgfältig wählen.",
        gradeNote: "Lange Routen im franz. 6–7. Bei einer 6 / 6a bleiben.",
        protectionNote: "Gute Haken an modernen Linien. Grad am Schild prüfen.",
        approach: "Achensee-Seite zum Klobenjoch.",
        descent: "Abseilen oder laut Topo.",
        weekend: "Samstag. Nicht in 7er geraten.",
        dont: ["Keine 7 versuchen, nur weil die 6 voll ist"],
        neighbor: "Rotspitz ist kürzer und moderater.",
        gear: ["60-m-Seil", "14 Exen", "Helm"]
      }
    }),
    pack({
      id: "hochiss-issplatten",
      rank: 47,
      name: "Issplatten",
      wall: "Hochiss",
      massif: "Rofan / Achensee",
      day: "sat",
      dayLabel: "Sat · high slabs",
      drive: "0:50–1:10",
      via: "B13 / Achenpass / Rofanbahn",
      aspect: "mixed",
      grade: "UIAA 5",
      gradeNote: "High Rofan slabs from the Bahn. Confirm the line is at or under 6 and not a south oven.",
      pitches: "several",
      protection: "alpine-bolted",
      protectionNote: "Sanierte high slabs. Take the Climbers Paradise topo.",
      why: "Same Bahn as Rotspitz. Height helps the heat if you pick the shadier slab.",
      approach: "Rofanbahn toward Hochiss / Issplatten.",
      descent: "Bahn or rappel per topo.",
      gear: ["60 m rope", "12 draws", "Helmet"],
      weekend: "Saturday. Check aspect on the exact slab.",
      dont: ["Assume every Hochiss line is north"],
      neighbor: "Hosentöter is the named north 5b.",
      topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/hochiss-issplatten/",
      topoImg: ROF,
      map: "https://www.openstreetmap.org/#map=14/47.447/11.76",
      lat: 47.4475,
      lng: 11.758,
      photos: [ROF_M],
      de: {
        dayLabel: "Sa · hohe Platten",
        via: "B13 / Achenpass / Rofanbahn",
        why: "Dieselbe Bahn wie Rotspitz. Höhe hilft, wenn die Platte schattig ist.",
        gradeNote: "Hohe Rofan-Platten. Linie max. 6, keine Süd-Ofen.",
        protectionNote: "Sanierte Platten. Climbers-Paradise-Topo.",
        approach: "Rofanbahn Richtung Hochiss / Issplatten.",
        descent: "Bahn oder abseilen.",
        weekend: "Samstag. Exposition der Platte prüfen.",
        dont: ["Nicht jede Hochiss-Linie ist Nord"],
        neighbor: "Hosentöter ist die benannte Nord-5b.",
        gear: ["60-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "guffert-suedkante",
      rank: 48,
      name: "Südkante",
      wall: "Guffert",
      massif: "Rofan / Steinberg",
      day: "sat",
      dayLabel: "Sat · south ridge 5+",
      drive: "0:45–1:00",
      via: "B13 / Achenpass / Steinberg",
      aspect: "S",
      grade: "UIAA 5+/6−",
      gradeNote: "300 m south ridge. At the cap. Wrong aspect for heat.",
      pitchCount: 10,
      pitches: "~300 m",
      protection: "alpine",
      protectionNote: "Alpine ridge, not plaisir.",
      why: "Very close via Achenpass. South — heat reject. Rätische Zeichen on the north is 6c+.",
      approach: "Steinberg, 2 h through pines to the south ridge.",
      descent: "Normal route north / Steinberg.",
      gear: ["60 m rope", "Draws, slings", "Helmet"],
      weekend: "Skip this heat weekend.",
      dont: ["Pick Guffert south for shade", "Default to Rätische Zeichen (over grade)"],
      neighbor: "Rotspitz north is the shade alternative 10 min further.",
      topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/guffert/",
      topoImg: ROF,
      map: "https://www.openstreetmap.org/#map=14/47.515/11.785",
      lat: 47.515,
      lng: 11.785,
      photos: [ROF_M],
      de: {
        dayLabel: "Sa · Südgrat 5+",
        via: "B13 / Achenpass / Steinberg",
        why: "Sehr nah über den Achenpass. Süd — bei Hitze tabu. Rätische Zeichen Nord ist 6c+.",
        gradeNote: "300 m Südgrat. An der Grenze. Falsche Seite für Hitze.",
        protectionNote: "Alpin-Grat, kein Plaisir.",
        approach: "Steinberg, 2 Std. durch Latschen zum Südgrat.",
        descent: "Normalweg Nord / Steinberg.",
        weekend: "Dieses Hitzewochenende lassen.",
        dont: ["Guffert Süd nicht für Schatten", "Rätische Zeichen nicht als erste Wahl (zu schwer)"],
        neighbor: "Rotspitz Nord ist die Schatten-Alternative, 10 Min. weiter.",
        gear: ["60-m-Seil", "Exen, Schlingen", "Helm"]
      }
    }),
    pack({
      id: "raetische-zeichen",
      rank: 49,
      overGrade: true,
      name: "Rätische Zeichen",
      wall: "Guffert Westgipfel Nordwand",
      massif: "Rofan / Steinberg",
      day: "sat",
      dayLabel: "Over grade",
      drive: "0:45–1:00",
      via: "B13 / Achenpass / Steinberg",
      aspect: "N",
      grade: "UIAA 6c+ / 8−",
      gradeNote: "6 pitches, 250 m, E1–2. True north, too hard.",
      pitches: "6 / 250 m",
      protection: "alpine-bolted",
      protectionNote: "14 draws, 50–60 m. The grade is the problem.",
      why: "Best north line on Guffert — over the cap. Listed last among Guffert options.",
      approach: "Steinberg to the north face of the west summit.",
      descent: "Per topo / ridge.",
      gear: ["50–60 m rope", "14 draws", "Helmet"],
      weekend: "Skip.",
      dont: ["Default to this after the grade lock"],
      neighbor: "No moderate north plaisir on Guffert.",
      topoPage: "https://www.alpines-klettern.de/neutouren/skripte/Raetische-Zeichen.pdf",
      topoImg: ROF,
      map: "https://www.openstreetmap.org/#map=14/47.518/11.782",
      lat: 47.518,
      lng: 11.782,
      photos: [ROF_M],
      de: {
        dayLabel: "Zu schwer",
        via: "B13 / Achenpass / Steinberg",
        why: "Beste Nordlinie am Guffert — über der Grenze.",
        gradeNote: "6 SL, 250 m, E1–2. Echte Nordwand, zu schwer.",
        protectionNote: "14 Exen, 50–60 m. Das Problem ist der Grad.",
        approach: "Steinberg zur Nordwand des Westgipfels.",
        descent: "Laut Topo / Grat.",
        weekend: "Lassen.",
        dont: ["Nicht als erste Wahl — über der Gradgrenze"],
        neighbor: "Kein moderates Nord-Plaisir am Guffert.",
        gear: ["50–60-m-Seil", "14 Exen", "Helm"]
      }
    }),
    pack({
      id: "kampen-torweg",
      rank: 50,
      name: "Torweg",
      wall: "Kampenwand Westgipfel",
      massif: "Chiemgauer Alpen",
      day: "sun",
      dayLabel: "Sun · west 4",
      drive: "1:00–1:20",
      via: "B472 / A8 / Kampenwandbahn",
      aspect: "W",
      grade: "UIAA 4",
      gradeNote: "80 m, about French 4. West — morning shade, afternoon sun.",
      pitches: "~80 m",
      protection: "alpine",
      protectionNote: "Classic. Some bolts.",
      why: "Sunday-east logistics, moderate. Not due north.",
      approach: "Bahn, west summit.",
      descent: "Ridge / Bahn.",
      gear: ["50 m rope", "Draws", "Helmet"],
      weekend: "Sunday early.",
      dont: ["Treat it as all-day north"],
      neighbor: "Nordgipfel Nordwand is the true-north short line.",
      topoPage: "https://www.bergsteigen.com/touren/klettern/kampenwand-ueberschreitung/",
      topoImg: KAM,
      map: "https://www.openstreetmap.org/#map=15/47.754/12.36",
      lat: 47.7538,
      lng: 12.3605,
      photos: [KAM_M],
      de: {
        dayLabel: "So · West 4",
        via: "B472 / A8 / Kampenwandbahn",
        why: "Sonntag-Osten-Logistik, moderat. Nicht genau Nord.",
        gradeNote: "80 m, etwa franz. 4. West — Vormittagsschatten.",
        protectionNote: "Klassiker. Einige Haken.",
        approach: "Bahn, Westgipfel.",
        descent: "Grat / Bahn.",
        weekend: "Sonntag früh.",
        dont: ["Nicht als Ganztags-Nord"],
        neighbor: "Nordgipfel-Nordwand ist die echte Nord-Kurzlinie.",
        gear: ["50-m-Seil", "Exen", "Helm"]
      }
    }),
    pack({
      id: "sparchen-5plus",
      rank: 51,
      name: "Sparchen 5+ start",
      wall: "Schanzer Wände / Sector A",
      massif: "Zahmer Kaiser / Inntal",
      day: "sun",
      dayLabel: "Sun · garden 5+",
      drive: "1:05–1:20",
      via: "B472 / A8 / A93 → Kufstein",
      aspect: "NW",
      grade: "UIAA 5+",
      gradeNote: "Easier garden MSL / first-pitch alternative. Not Möwe Jonathan.",
      pitches: "1–3",
      protection: "plaisir",
      protectionNote: "Fully bolted. Shade until ~14:00.",
      why: "Best Sunday bolt-grid if you already drive to Kufstein. Stay in the garden.",
      approach: "Kaisertalstraße barrier, 2–5 min to Sector A.",
      descent: "Rappel.",
      gear: ["60 m rope", "14 draws", "Helmet"],
      weekend: "Sunday morning. Off by 13:00.",
      dont: ["Climb Möwe Jonathan (7+)"],
      neighbor: "The garden has more 5–6 sport MSL.",
      topoPage: "https://www.stadler-markus.de/alpinklettern/wilder-kaiser/kletterroute/moewe-jonathan.html",
      topoImg: "assets/media/3b8e389f4251.png",
      map: "https://www.openstreetmap.org/#map=16/47.592/12.185",
      lat: 47.5928,
      lng: 12.1864,
      photos: [SPA],
      de: {
        dayLabel: "So · Garten 5+",
        via: "B472 / A8 / A93 → Kufstein",
        why: "Bestes Sonntags-Bohrhakenraster, wenn ihr schon nach Kufstein fahrt. Im Garten bleiben.",
        gradeNote: "Leichtere Garten-Mehrseillängen / Alternativeinstieg. Nicht Möwe Jonathan.",
        protectionNote: "Durchgehend gebohrt. Schatten bis ca. 14:00.",
        approach: "Schranke Kaisertalstraße, 2–5 Min. zu Sektor A.",
        descent: "Abseilen.",
        weekend: "Sonntag vormittag. 13:00 fertig.",
        dont: ["Möwe Jonathan nicht (7+)"],
        neighbor: "Im Garten gibt es mehr Sport-Mehrseillängen im 5. und 6. Grad.",
        gear: ["60-m-Seil", "14 Exen", "Helm"]
      }
    }),
    pack({
      id: "moewe-jonathan",
      rank: 52,
      overGrade: true,
      name: "Möwe Jonathan",
      wall: "Schanzer Wände",
      massif: "Zahmer Kaiser / Inntal",
      day: "sun",
      dayLabel: "Over grade",
      drive: "1:05–1:20",
      via: "B472 / A8 / A93 → Kufstein",
      aspect: "NW",
      grade: "UIAA 7+",
      gradeNote: "The famous Sparchen line. 7+. Over the lock.",
      pitches: "several",
      protection: "plaisir",
      protectionNote: "Perfect bolts. Wrong grade.",
      why: "Listed so nobody 'just tries the classic'.",
      approach: "Sector A, 2 min.",
      descent: "Rappel.",
      gear: ["60 m double", "14 draws", "Helmet"],
      weekend: "Skip.",
      dont: ["Default to this"],
      neighbor: "Garden 5–6 only.",
      topoPage: "https://www.stadler-markus.de/alpinklettern/wilder-kaiser/kletterroute/moewe-jonathan.html",
      topoImg: "assets/media/3b8e389f4251.png",
      map: "https://www.openstreetmap.org/#map=16/47.592/12.186",
      lat: 47.5925,
      lng: 12.187,
      photos: [SPA],
      de: {
        dayLabel: "Zu schwer",
        via: "B472 / A8 / A93 → Kufstein",
        why: "Steht hier, damit niemand „nur mal den Klassiker“ macht.",
        gradeNote: "Die berühmte Sparchen-Linie. 7+. Über der Grenze.",
        protectionNote: "Perfekte Haken. Falscher Grad.",
        approach: "Sektor A, 2 Min.",
        descent: "Abseilen.",
        weekend: "Lassen.",
        dont: ["Nicht als erste Wahl"],
        neighbor: "Nur Garten 5–6.",
        gear: ["60-m-Doppelseil", "14 Exen", "Helm"]
      }
    }),
    pack({
      id: "gnadenlosen-drei",
      rank: 53,
      name: "Die Gnadenlosen Drei",
      wall: "Hörndlwand",
      massif: "Chiemgauer Alpen",
      day: "sun",
      dayLabel: "Sun east · ~2 h",
      drive: "1:50–2:15",
      via: "A8 / Ruhpolding / Seehaus",
      aspect: "NE / N",
      grade: "UIAA 5",
      gradeNote: "8 pitches at 5. Flag: drive is at the 2 h edge from Tölz.",
      pitches: "8 / ~200 m",
      protection: "alpine-bolted",
      protectionNote: "Neighbor lines retro-bolted; verify this one live.",
      why: "True moderate north-east. The drive from Tölz is the problem.",
      approach: "Seehaus → Hörndlalm, 1.5–2 h / 750 Hm.",
      descent: "Ridge west, Hörndlalm.",
      gear: ["50–60 m rope", "10 draws", "Helmet"],
      weekend: "Only if you accept a long east transfer.",
      dont: ["Climb Gelbe Wand (7−)"],
      neighbor: "Neuer Schmidkunzweg is the 3+ on the same peak.",
      topoPage: "https://www.stadler-markus.de/klettern/hoerndlwand.html",
      topoImg: "assets/media/32f35e1122fe.jpg",
      map: "https://www.openstreetmap.org/#map=14/47.711/12.622",
      lat: 47.6848,
      lng: 12.6364,
      photos: ["assets/media/3280077b40fb.jpg"],
      de: {
        dayLabel: "So Osten · ~2 Std.",
        via: "A8 / Ruhpolding / Seehaus",
        why: "Moderat, Nordost. Die Anfahrt ab Tölz ist das Problem.",
        gradeNote: "8 SL im 5. Anfahrt an der 2-Std-Grenze.",
        protectionNote: "Nachbarlinien saniert; diese live prüfen.",
        approach: "Seehaus → Hörndlalm, 1,5–2 Std.",
        descent: "Grat westlich, Hörndlalm.",
        weekend: "Nur bei langer Ost-Anfahrt.",
        dont: ["Gelbe Wand nicht (7−)"],
        neighbor: "Neuer Schmidkunzweg ist die 3+ am selben Berg.",
        gear: ["50–60-m-Seil", "10 Exen", "Helm"]
      }
    }),
    pack({
      id: "schmidkunzweg",
      rank: 54,
      name: "Neuer Schmidkunzweg",
      wall: "Hörndlwand",
      massif: "Chiemgauer Alpen",
      day: "sun",
      dayLabel: "Sun · easy · far",
      drive: "1:50–2:15",
      via: "A8 / Seehaus",
      aspect: "N / NE",
      grade: "UIAA 3+",
      gradeNote: "Easy alpine mountain route. Long drive from Tölz.",
      pitches: "short pitches + walking",
      protection: "alpine",
      protectionNote: "Not a bolt grid.",
      why: "Easy north-east. Drive kills the match score.",
      approach: "Seehaus → Hörndlalm, 1.5–2 h.",
      descent: "Hörndlalm path.",
      gear: ["50 m rope", "Slings", "Helmet"],
      weekend: "Prefer Buchstein if you want easy and close.",
      dont: ["Expect bolts every 2 m"],
      neighbor: "Gnadenlosen Drei is the 5.",
      topoPage: "https://www.alpenvereinaktiv.com/de/tour/neuer-schmidkunzweg-iii-auf-die-hoerndlwand-1684-m-/808280149/",
      topoImg: "assets/media/32f35e1122fe.jpg",
      map: "https://www.openstreetmap.org/#map=14/47.711/12.622",
      lat: 47.6856,
      lng: 12.6348,
      photos: ["assets/media/3280077b40fb.jpg"],
      de: {
        dayLabel: "So · leicht · weit",
        via: "A8 / Seehaus",
        why: "Leicht, Nordost. Die Anfahrt drückt den Match.",
        gradeNote: "Leichte alpine Bergtour. Lange Anfahrt ab Tölz.",
        protectionNote: "Kein Bohrhakenraster.",
        approach: "Seehaus → Hörndlalm, 1,5–2 Std.",
        descent: "Hörndlalm.",
        weekend: "Lieber Buchstein, wenn leicht und nah.",
        dont: ["Keine Haken alle 2 m"],
        neighbor: "Gnadenlosen Drei ist die 5.",
        gear: ["50-m-Seil", "Schlingen", "Helm"]
      }
    }),
    pack({
      id: "mitteldurchstieg",
      rank: 55,
      name: "Mitteldurchstieg",
      wall: "Rotspitz Südwand",
      massif: "Rofan / Achensee",
      day: "sat",
      dayLabel: "Sat · high 4b · south",
      drive: "0:50–1:10",
      via: "B13 / Achenpass / Rofanbahn",
      aspect: "S",
      grade: "UIAA 4b / 4a obl.",
      gradeNote: "2 pitches, retro-bolted. Easy grade, wrong aspect.",
      pitches: "2 / 50 m",
      protection: "alpine-bolted",
      protectionNote: "Sanierte. Rap or walk off.",
      why: "Only as a tiny 4 after a north pitch. Oven after 09:30.",
      approach: "Rofanbahn → Rotspitz south, 45 min.",
      descent: "Normalweg or chimney 40 m.",
      gear: ["60 m double", "10 draws", "Helmet"],
      weekend: "Not a heat A-plan.",
      dont: ["Pick this for shade"],
      neighbor: "Hosentöter around the corner is north.",
      topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/rotspitz/",
      topoImg: "assets/topos/mitteldurchstieg.jpg",
      map: "https://www.openstreetmap.org/#map=15/47.441/11.761",
      lat: 47.4412,
      lng: 11.7604,
      photos: ["assets/media/8ad570a58754.jpg"],
      de: {
        dayLabel: "Sa · hoch 4b · Süd",
        via: "B13 / Achenpass / Rofanbahn",
        why: "Nur als Mini-4 nach einer Nordlänge. Ab 9:30 Ofen.",
        gradeNote: "2 SL, saniert. Leicht, falsche Seite.",
        protectionNote: "Saniert. Abseilen oder zu Fuß.",
        approach: "Rofanbahn → Rotspitz Süd, 45 Min.",
        descent: "Normalweg oder Kamin 40 m.",
        weekend: "Kein Hitze-A-Plan.",
        dont: ["Nicht für Schatten"],
        neighbor: "Hosentöter um die Ecke ist Nord.",
        gear: ["60-m-Doppelseil", "10 Exen", "Helm"]
      }
    }),
    pack({
      id: "ellmauer-tor",
      rank: 56,
      name: "Plaisir am Ellmauer Tor",
      wall: "Ellmauer Tor",
      massif: "Wilder Kaiser",
      day: "sun",
      dayLabel: "Sun · easy Kaiser",
      drive: "1:25–1:45",
      via: "A8 / Ellmau / Wochenbrunner Alm",
      aspect: "mixed",
      grade: "UIAA 3–4",
      gradeNote: "Mostly III; be solid in IV. Classic easy alpine.",
      pitches: "several",
      protection: "alpine",
      protectionNote: "Mixed; some bolts.",
      why: "Sunday-east scenery. Not a bolt grid. Longer drive than Buchstein.",
      approach: "Wochenbrunner Alm toward Gruttenhütte.",
      descent: "Marked paths / hut.",
      gear: ["50 m rope", "Draws", "Slings", "Helmet"],
      weekend: "Sunday early. Busy hiking zone.",
      dont: ["Treat III as a via ferrata"],
      neighbor: "Scheffauer north is the serious Kaiser pick.",
      topoPage: "https://www.via-ferrata.de/touren/gps/plaisir-kletterroute-ellmauer-tor-wilder-kaiser",
      topoImg: KAI,
      map: "https://www.openstreetmap.org/#map=14/47.567/12.303",
      lat: 47.5668,
      lng: 12.3028,
      photos: [KAI_M],
      de: {
        dayLabel: "So · leichter Kaiser",
        via: "A8 / Ellmau / Wochenbrunner Alm",
        why: "Sonntag Osten, große Kulisse. Keine dichte Bohrhakenabsicherung. Länger als Buchstein.",
        gradeNote: "Meist III; IV beherrschen.",
        protectionNote: "Gemischt, einige Haken.",
        approach: "Wochenbrunner Alm Richtung Gruttenhütte.",
        descent: "Markierte Steige / Hütte.",
        weekend: "Sonntag früh. Wandergebiet.",
        dont: ["III nicht wie Klettersteig"],
        neighbor: "Scheffauer Nord ist die ernste Kaiser-Wahl.",
        gear: ["50-m-Seil", "Exen", "Schlingen", "Helm"]
      }
    }),
    pack({
      id: "multerkar-abenteurer",
      rank: 57,
      name: "Tour für Abenteurer",
      wall: "Multerkarwand / Treffauer",
      massif: "Kaisergebirge",
      day: "sun",
      dayLabel: "Sun · SW 6",
      drive: "1:00–1:20",
      via: "A8 / Scheffau / Jägerwirt",
      aspect: "SW",
      grade: "UIAA 6",
      gradeNote: "At the cap. Well bolted. SW — not shade.",
      pitches: "several / ~200 m+",
      protection: "plaisir",
      protectionNote: "Good bolts. Rappel 50 + 20 m.",
      why: "Kaiser plaisir at 6. Wrong aspect for heat.",
      approach: "1–1.5 h from Jägerwirt. e-bike friendly.",
      descent: "Rappel the line.",
      gear: ["50 m rope", "12 draws", "Helmet"],
      weekend: "Only a very early cool morning.",
      dont: ["Pick this for north shade"],
      neighbor: "Multerkar has easier 5s on Climbers Paradise.",
      topoPage: "https://www.bergsteigen.com/touren/klettern/tour-fuer-abenteurer-multerkarwand/",
      topoImg: KAI,
      map: "https://www.openstreetmap.org/#map=15/47.555/12.205",
      lat: 47.5553,
      lng: 12.2054,
      photos: [KAI_M],
      de: {
        dayLabel: "So · SW 6",
        via: "A8 / Scheffau / Jägerwirt",
        why: "Kaiser-Plaisir im 6. Falsche Seite für Hitze.",
        gradeNote: "An der Grenze. Gut gebohrt. SW — kein Schatten.",
        protectionNote: "Gute Haken. Abseilen 50 + 20 m.",
        approach: "1–1,5 Std. vom Jägerwirt. E-Bike.",
        descent: "Über die Route abseilen.",
        weekend: "Nur sehr früher kühler Morgen.",
        dont: ["Nicht für Nordschatten"],
        neighbor: "Multerkar hat leichtere 5er auf Climbers Paradise.",
        gear: ["50-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "geiselstein-ballisto",
      rank: 58,
      name: "Ballisto",
      wall: "Geiselstein Südwand",
      massif: "Ammergauer Alpen",
      day: "sat",
      dayLabel: "Sat · south reject",
      drive: "1:10–1:25",
      via: "B472 / Weilheim / Halblech",
      aspect: "S",
      grade: "UIAA 6",
      gradeNote: "South face. Heat reject. At the cap.",
      pitches: "multi-pitch",
      protection: "alpine-bolted",
      protectionNote: "Better bolted than Herzogweg; wrong sky.",
      why: "Listed so nobody 'just goes around the corner' on a heat Saturday.",
      approach: "Same as Herzogweg to Wankerfleck, then south.",
      descent: "Normal route.",
      gear: ["60 m rope", "12 draws", "Helmet"],
      weekend: "Skip.",
      dont: ["Pair this with Herzogweg on a 35 °C day"],
      neighbor: "Herzogweg is the north line.",
      topoPage: "https://www.hikr.org/tour/post155013.html",
      topoImg: GEI,
      map: "https://www.openstreetmap.org/#map=15/47.574/10.808",
      lat: 47.574,
      lng: 10.808,
      photos: [GEI],
      de: {
        dayLabel: "Sa · Süd tabu",
        via: "B472 / Weilheim / Halblech",
        why: "Steht hier, damit niemand „kurz um die Ecke“ an einem 35°-Samstag geht.",
        gradeNote: "Südwand. Bei Hitze tabu. An der Grenze.",
        protectionNote: "Besser gebohrt als Herzogweg; falscher Himmel.",
        approach: "Wie Herzogweg zum Wankerfleck, dann Süd.",
        descent: "Normalweg.",
        weekend: "Lassen.",
        dont: ["Nicht mit Herzogweg an einem 35°-Tag koppeln"],
        neighbor: "Herzogweg ist die Nordlinie.",
        gear: ["60-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "lebe-deinen-traum",
      rank: 59,
      overGrade: true,
      name: "Lebe deinen Traum",
      wall: "Benediktenwand Nord",
      massif: "Bayerische Voralpen",
      day: "sat",
      dayLabel: "Over grade",
      drive: "0:20–0:35",
      via: "B472 / Tutzinger Hütte",
      aspect: "N",
      grade: "UIAA 7",
      gradeNote: "11 pitches, 340 m, fully bolted. Consistent 6+/7. theCrag classic. Over the cap.",
      pitchCount: 11,
      pitches: "11 / 340 m",
      protection: "plaisir",
      protectionNote: "Perfect bolts. Grade 7.",
      why: "Best modern north line on the Hausberg — too hard.",
      approach: "Tutzinger Hütte, Rampe-Rippe sector.",
      descent: "Walk-off / rappel sections.",
      gear: ["60 m rope", "13 draws", "Helmet"],
      weekend: "Skip.",
      dont: ["Default to this because it is bolted and north"],
      neighbor: "Rampen-Rippe is the 4+.",
      topoPage: "https://www.bergsteigen.com/touren/klettern/lebe-deinen-traum-benediktenwand/",
      topoImg: LEBE,
      map: "https://www.openstreetmap.org/#map=15/47.654/11.462",
      lat: 47.6543,
      lng: 11.4622,
      photos: [LEBE],
      de: {
        dayLabel: "Zu schwer",
        via: "B472 / Tutzinger Hütte",
        why: "Beste moderne Nordlinie am Hausberg — zu schwer.",
        gradeNote: "11 SL, 340 m, durchgehend gebohrt. Konstant 6+/7.",
        protectionNote: "Perfekte Haken. Grad 7.",
        approach: "Tutzinger Hütte, Rampe-Rippe-Sektor.",
        descent: "Zu Fuß / teils abseilen.",
        weekend: "Lassen.",
        dont: ["Nicht als erste Wahl, nur weil gebohrt und Nord"],
        neighbor: "Rampen-Rippe ist die 4+.",
        gear: ["60-m-Seil", "13 Exen", "Helm"]
      }
    }),
    pack({
      id: "cavemen",
      rank: 60,
      overGrade: true,
      name: "Cavemen",
      wall: "Benediktenwand Nord",
      massif: "Bayerische Voralpen",
      day: "sat",
      dayLabel: "Over grade",
      drive: "0:20–0:35",
      via: "B472 / Tutzinger Hütte",
      aspect: "N",
      grade: "UIAA 7",
      gradeNote: "Modern bolted north line. Over the cap.",
      pitches: "several",
      protection: "plaisir",
      protectionNote: "One of the few fully bolted Bene lines. Grade 7.",
      why: "Home-wall plaisir — too hard.",
      approach: "Tutzinger Hütte.",
      descent: "Rappel / walk-off.",
      gear: ["60 m rope", "12 draws", "Helmet"],
      weekend: "Skip.",
      dont: ["Default to this"],
      neighbor: "Rampen-Rippe.",
      topoPage: "https://www.stadler-markus.de/klettern/benediktenwand.html",
      topoImg: LEBE,
      map: "https://www.openstreetmap.org/#map=15/47.654/11.463",
      lat: 47.6545,
      lng: 11.463,
      photos: [LEBE],
      de: {
        dayLabel: "Zu schwer",
        via: "B472 / Tutzinger Hütte",
        why: "Hausberg-Plaisir — zu schwer.",
        gradeNote: "Moderne gebohrte Nordlinie. Über der Grenze.",
        protectionNote: "Eine der wenigen durchgehend gebohrten Bene-Linien. Grad 7.",
        approach: "Tutzinger Hütte.",
        descent: "Abseilen / zu Fuß.",
        weekend: "Lassen.",
        dont: ["Nicht als erste Wahl"],
        neighbor: "Rampen-Rippe.",
        gear: ["60-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "direkte-rippe",
      rank: 61,
      overGrade: true,
      name: "Direkte Rippe",
      wall: "Benediktenwand Nord",
      massif: "Bayerische Voralpen",
      day: "sat",
      dayLabel: "Over grade",
      drive: "0:20–0:35",
      via: "B472 / Tutzinger Hütte",
      aspect: "N",
      grade: "UIAA 7",
      gradeNote: "The direct finish of Rampe-Rippe. 7 (6−/A0). Do not wander onto it from the 4+.",
      pitches: "3 / 100 m variant",
      protection: "alpine-bolted",
      protectionNote: "Bolts on the hard bits. Grade is the issue.",
      why: "The trap on the Hausberg classic.",
      approach: "Same as Rampen-Rippe, then the direct rib.",
      descent: "Walk-off.",
      gear: ["60 m rope", "10 draws", "Helmet"],
      weekend: "Stay on the original 4+.",
      dont: ["Leave the original Rampe-Rippe for this"],
      neighbor: "Rampen-Rippe original.",
      topoPage: "https://www.thecrag.com/en/climbing/germany/route/4024450698",
      topoImg: BENE,
      map: "https://www.openstreetmap.org/#map=15/47.654/11.462",
      lat: 47.654,
      lng: 11.4615,
      photos: [BENE_M],
      de: {
        dayLabel: "Zu schwer",
        via: "B472 / Tutzinger Hütte",
        why: "Die Falle am Hausberg-Klassiker.",
        gradeNote: "Direktausstieg der Rampe-Rippe. 7 (6−/A0). Nicht von der 4+ dahin irren.",
        protectionNote: "Haken an den schweren Stellen. Grad ist das Problem.",
        approach: "Wie Rampen-Rippe, dann direkte Rippe.",
        descent: "Zu Fuß.",
        weekend: "Auf der Original-4+ bleiben.",
        dont: ["Nicht von der Rampe-Rippe hierher"],
        neighbor: "Rampen-Rippe original.",
        gear: ["60-m-Seil", "10 Exen", "Helm"]
      }
    }),
    pack({
      id: "brauneck-msl",
      rank: 62,
      name: "Brauneck 2-pitch",
      wall: "Brauneck / Lenggries",
      massif: "Bayerische Voralpen",
      day: "sun",
      dayLabel: "Sun · 10 min · short",
      drive: "0:10–0:20",
      via: "B13 / Lenggries / Brauneckbahn",
      aspect: "mixed",
      grade: "UIAA 5",
      gradeNote: "Most Brauneck lines are 1 pitch. A few 2-pitch sport lines exist (Stadler). Pick N/NW sector if hot. Max 6.",
      pitches: "2 / ~40–60 m",
      protection: "plaisir",
      protectionNote: "Sport bolts. Not an alpine day.",
      why: "Closest rock from Tölz. Use as Sunday backup, not the multi-pitch dream.",
      approach: "Lenggries valley station / Stie-Alm sectors.",
      descent: "Rappel.",
      gear: ["60 m rope", "12 draws", "Helmet"],
      weekend: "Sunday if weather dies. Check sector aspect.",
      dont: ["Call this a north-wall alpine day", "Climb a 7 because it is 10 minutes away"],
      neighbor: "Benediktenwand is the real local multi-pitch.",
      topoPage: "https://www.stadler-markus.de/klettern/brauneck-klettern-am-lenggrieser-hausberg.html",
      topoImg: "",
      map: "https://www.openstreetmap.org/#map=14/47.681/11.574",
      lat: 47.681,
      lng: 11.574,
      photos: [],
      de: {
        dayLabel: "So · 10 Min. · kurz",
        via: "B13 / Lenggries / Brauneckbahn",
        why: "Nächster Fels ab Tölz. Sonntag-Backup, kein Alpintraum.",
        gradeNote: "Die meisten Linien 1 SL. Einige 2-SL-Sport. Bei Hitze N/NW. Max 6.",
        protectionNote: "Sport-Haken. Kein Alphtag.",
        approach: "Lenggries Talstation / Stie-Alm-Sektoren.",
        descent: "Abseilen.",
        weekend: "Sonntag, wenn das Wetter kippt. Sektor-Exposition prüfen.",
        dont: ["Nicht als Nordwand-Alphtag", "Keine 7, nur weil 10 Minuten"],
        neighbor: "Benediktenwand ist die echte lokale Mehrseillänge.",
        gear: ["60-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "probstenwand",
      rank: 63,
      name: "Probstenwand",
      wall: "Probstenwand",
      massif: "Tölzer Land",
      day: "sun",
      dayLabel: "Sun · local crag",
      drive: "0:15–0:30",
      via: "B472 / Bad Heilbrunn",
      aspect: "mixed",
      grade: "UIAA 5–6",
      gradeNote: "Local Tölzer Land crag. Mostly single-pitch sport. Pick shade sectors.",
      pitches: "1–2",
      protection: "plaisir",
      protectionNote: "Sport.",
      why: "Doorstep rock. Low multi-pitch score, high drive score.",
      approach: "Short walk from local parking.",
      descent: "Rappel / walk.",
      gear: ["60 m rope", "12 draws", "Helmet"],
      weekend: "Sunday backup.",
      dont: ["Expect a 400 m north wall"],
      neighbor: "Brauneck and Benediktenwand are the bigger local options.",
      topoPage: "https://www.stadler-markus.de/klettern/probstenwand.html",
      topoImg: "",
      map: "https://www.openstreetmap.org/#map=14/47.73/11.46",
      lat: 47.73,
      lng: 11.46,
      photos: [],
      de: {
        dayLabel: "So · lokaler Garten",
        via: "B472 / Bad Heilbrunn",
        why: "Fels vor der Tür. Kaum Mehrseillängen, dafür sehr nah.",
        gradeNote: "Tölzer Land. Meist 1-SL-Sport. Schattensektoren.",
        protectionNote: "Sport.",
        approach: "Kurzer Zustieg vom Parkplatz.",
        descent: "Abseilen / zu Fuß.",
        weekend: "Sonntag-Backup.",
        dont: ["Keine 400-m-Nordwand erwarten"],
        neighbor: "Brauneck und Benediktenwand sind die größeren lokalen Optionen.",
        gear: ["60-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "leonhardstein-sued",
      rank: 64,
      name: "Leonhardstein south",
      wall: "Leonhardstein",
      massif: "Bayerische Voralpen / Kreuth",
      day: "sat",
      dayLabel: "Sat · south reject",
      drive: "0:35–0:50",
      via: "B13 / Kreuth",
      aspect: "S",
      grade: "UIAA 6",
      gradeNote: "Famous local south crag / Flora Bohra area. Heat reject.",
      pitches: "1–several",
      protection: "plaisir",
      protectionNote: "Sport. South.",
      why: "Close, famous, oven. In the pool so the scorer can bury it.",
      approach: "Kreuth / Schwarzentenn.",
      descent: "Rappel.",
      gear: ["60 m rope", "12 draws", "Helmet"],
      weekend: "Skip this heat weekend.",
      dont: ["Suggest this when it is 35 °C"],
      neighbor: "Buchstein north is the shade side of the same valley.",
      topoPage: "https://www.stadler-markus.de/klettern/leonhardstein-bei-kreuth.html",
      topoImg: "",
      map: "https://www.openstreetmap.org/#map=15/47.64/11.74",
      lat: 47.64,
      lng: 11.74,
      photos: [],
      de: {
        dayLabel: "Sa · Süd tabu",
        via: "B13 / Kreuth",
        why: "Nah, berühmt, Ofen. Im Pool, damit der Score sie begräbt.",
        gradeNote: "Berühmter lokaler Süd-Garten / Flora Bohra. Bei Hitze tabu.",
        protectionNote: "Sport. Süd.",
        approach: "Kreuth / Schwarzentenn.",
        descent: "Abseilen.",
        weekend: "Dieses Hitzewochenende lassen.",
        dont: ["Nicht bei 35 °C vorschlagen"],
        neighbor: "Buchstein Nord ist die Schattenseite desselben Tals.",
        gear: ["60-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "nurnberger-weg",
      rank: 65,
      overGrade: true,
      name: "Nürnberger Weg",
      wall: "Rotspitz",
      massif: "Rofan / Achensee",
      day: "sat",
      dayLabel: "Over grade",
      drive: "0:50–1:10",
      via: "B13 / Achenpass / Rofanbahn",
      aspect: "N",
      grade: "6b",
      gradeNote: "Neighbor of Hosentöter. 6b. Over the lock.",
      pitches: "short MSL",
      protection: "mixed",
      protectionNote: "Bolts + cams.",
      why: "Same north sector — too hard.",
      approach: "As Hosentöter.",
      descent: "Rappel.",
      gear: ["60 m double", "10 draws", "Cams", "Helmet"],
      weekend: "Skip.",
      dont: ["Confuse with Hosentöter (5b)"],
      neighbor: "Hosentöter is the 5b.",
      topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/rotspitz/",
      topoImg: ROF,
      map: "https://www.openstreetmap.org/#map=14/47.442/11.762",
      lat: 47.4419,
      lng: 11.7615,
      photos: [ROF_M],
      de: {
        dayLabel: "Zu schwer",
        via: "B13 / Achenpass / Rofanbahn",
        why: "Derselbe Nordsektor — zu schwer.",
        gradeNote: "Nachbar von Hosentöter. 6b. Über der Grenze.",
        protectionNote: "Haken + Friends.",
        approach: "Wie Hosentöter.",
        descent: "Abseilen.",
        weekend: "Lassen.",
        dont: ["Nicht mit Hosentöter (5b) verwechseln"],
        neighbor: "Hosentöter ist die 5b.",
        gear: ["60-m-Doppelseil", "10 Exen", "Friends", "Helm"]
      }
    }),
    pack({
      id: "zahmer-kaiser",
      rank: 66,
      name: "Zahmer Kaiser MSL",
      wall: "Zahmer Kaiser",
      massif: "Kaisergebirge + Inntal",
      day: "sun",
      dayLabel: "Sun east filler",
      drive: "1:05–1:20",
      via: "B472 / A8 / A93 / Kaisertal",
      aspect: "mixed",
      grade: "UIAA 5–6",
      gradeNote: "Confirm the wall is N/NW and max 6 the night before.",
      pitches: "various",
      protection: "mixed",
      protectionNote: "No single north plaisir. Prefer Sparchen garden or Scheffauer.",
      why: "East-side filler if named walls are slammed.",
      approach: "Depends on the wall.",
      descent: "Per topo.",
      gear: ["60 m rope", "12 draws", "Helmet"],
      weekend: "Prefer a named north line.",
      dont: ["Pick a wall without checking aspect and max grade"],
      neighbor: "Sparchen garden.",
      topoPage: "https://www.climbers-paradise.com/kletterregionen/kufsteinerland/mehrseillaengen/",
      topoImg: "assets/topos/sparchen.png",
      map: "https://www.openstreetmap.org/#map=13/47.595/12.210",
      lat: 47.5984,
      lng: 12.2186,
      photos: [SPA],
      de: {
        dayLabel: "So Osten, Lückenfüller",
        via: "B472 / A8 / A93 / Kaisertal",
        why: "Osten-Füller, wenn die benannten Wände voll sind.",
        gradeNote: "Wand am Vorabend auf N/NW und max. 6 prüfen.",
        protectionNote: "Kein einzelnes Nord-Plaisir. Lieber Sparchen oder Scheffauer.",
        approach: "Hängt von der Wand ab.",
        descent: "Laut Topo.",
        weekend: "Lieber eine benannte Nordlinie.",
        dont: ["Keine Wand ohne Exposition und Max-Grad"],
        neighbor: "Sparchen-Garten.",
        gear: ["60-m-Seil", "12 Exen", "Helm"]
      }
    }),
    pack({
      id: "lichtenluecke",
      rank: 67,
      name: "Lichterkette",
      wall: "Rotspitz",
      massif: "Rofan / Achensee",
      day: "sat",
      dayLabel: "Sat · high · caution",
      drive: "0:50–1:10",
      via: "B13 / Achenpass / Rofanbahn",
      aspect: "mixed",
      grade: "UIAA 5",
      gradeNote: "Climbers Paradise warning: loose blocks at the start, second bolt on a block. Confirm grade live. Moderate if still open.",
      pitches: "several",
      protection: "mixed",
      protectionNote: "Check the danger board. Loose rock.",
      why: "Same peak as Hosentöter. Only if the warning is cleared.",
      approach: "Rofanbahn → Rotspitz.",
      descent: "Rappel / walk.",
      gear: ["60 m double", "10 draws", "Helmet"],
      weekend: "Read the Gefahrenmeldung first.",
      dont: ["Climb under the loose start"],
      neighbor: "Hosentöter is the cleaner north 5b.",
      topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/location/rotspitz/",
      topoImg: ROF,
      map: "https://www.openstreetmap.org/#map=15/47.442/11.762",
      lat: 47.4422,
      lng: 11.7612,
      photos: [ROF_M],
      de: {
        dayLabel: "Sa · hoch · Vorsicht",
        via: "B13 / Achenpass / Rofanbahn",
        why: "Gleicher Berg wie Hosentöter. Nur wenn die Warnung weg ist.",
        gradeNote: "Lose Blöcke am Einstieg, 2. Haken auf einem Block. Grad live prüfen.",
        protectionNote: "Gefahrenmeldung lesen. Lockeres Gestein.",
        approach: "Rofanbahn → Rotspitz.",
        descent: "Abseilen / zu Fuß.",
        weekend: "Zuerst die Gefahrenmeldung.",
        dont: ["Nicht unter dem losen Einstieg"],
        neighbor: "Hosentöter ist die sauberere Nord-5b.",
        gear: ["60-m-Doppelseil", "10 Exen", "Helm"]
      }
    }),
    pack({
      id: "lamsenspitze",
      rank: 68,
      name: "Lamsenspitze MSL",
      wall: "Lamsenspitze",
      massif: "Karwendel / Achensee",
      day: "sat",
      dayLabel: "Sat · alpine mixed",
      drive: "0:55–1:15",
      via: "B13 / Achenpass / Pertisau / Gramai",
      aspect: "N",
      grade: "UIAA 5",
      gradeNote: "Partly retro-bolted. Take extra gear. Dreamland crag sits below.",
      pitches: "several",
      protection: "mixed",
      protectionNote: "Not plaisir. Nuts/friends required.",
      why: "Karwendel north-ish, Achenpass-close. Alpine, not a bolt grid.",
      approach: "Gramai / Lamsenjoch area.",
      descent: "Per topo / hut.",
      gear: ["60 m rope", "Draws", "Rack", "Helmet"],
      weekend: "Saturday if you want alpine Karwendel under 6.",
      dont: ["Leave the rack at home"],
      neighbor: "Gramai MSL is the more bolted option.",
      topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/",
      topoImg: ROF,
      map: "https://www.openstreetmap.org/#map=14/47.38/11.60",
      lat: 47.38,
      lng: 11.605,
      photos: [ROF_M],
      de: {
        dayLabel: "Sa · alpin gemischt",
        via: "B13 / Achenpass / Pertisau / Gramai",
        why: "Karwendel eher Nord, Achenpass-nah. Alpin, keine dichte Absicherung.",
        gradeNote: "Teilweise saniert. Extra-Material. Dreamland-Garten darunter.",
        protectionNote: "Kein Plaisir. Keile/Friends nötig.",
        approach: "Gramai / Lamsenjoch.",
        descent: "Laut Topo / Hütte.",
        weekend: "Samstag für alpines Karwendel unter 6.",
        dont: ["Klemmzeug nicht vergessen"],
        neighbor: "Gramai ist die besser gebohrte Option.",
        gear: ["60-m-Seil", "Exen", "Klemmzeug", "Helm"]
      }
    }),
    pack({
      id: "soiern-grat",
      rank: 69,
      name: "Soiern ridge",
      wall: "Soierngruppe",
      massif: "Karwendel",
      day: "sat",
      dayLabel: "Sat · alpine ridge",
      drive: "0:40–0:55",
      via: "B13 / Krün / Vorderriß",
      aspect: "mixed",
      grade: "UIAA 3–4",
      gradeNote: "Alpine ridge / mountain route, not sport multi-pitch. Close from Tölz.",
      pitches: "ridge + short pitches",
      protection: "alpine",
      protectionNote: "Terrain, some bolts/pins. Alpine sense.",
      why: "Very close Karwendel. Shade is mixed. Good if you want a mountain day, not a bolt grid.",
      approach: "Krün / Vorderriß toward Soiernspitze / Soiernhaus.",
      descent: "Normal paths.",
      gear: ["50 m rope", "Slings", "Helmet"],
      weekend: "Saturday mountain day. Not the well-protected pick.",
      dont: ["Call it plaisir"],
      neighbor: "Benediktenwand is the closer north wall.",
      topoPage: "https://www.thecrag.com/en/climbing/germany/area/400556487",
      topoImg: "",
      map: "https://www.openstreetmap.org/#map=13/47.505/11.279",
      lat: 47.505,
      lng: 11.279,
      photos: [],
      de: {
        dayLabel: "Sa · Alpin-Grat",
        via: "B13 / Krün / Vorderriß",
        why: "Sehr nahes Karwendel. Schatten gemischt. Ein Bergtag, keine Sportkletterei.",
        gradeNote: "Alpin-Grat und Bergtour, keine Sport-Mehrseillänge. Nah ab Tölz.",
        protectionNote: "Gelände, einige Haken. Alpines Auge.",
        approach: "Krün / Vorderriß zur Soiernspitze / Soiernhaus.",
        descent: "Normalwege.",
        weekend: "Samstag Bergtag. Nicht die gut abgesicherte Wahl.",
        dont: ["Nicht Plaisir nennen"],
        neighbor: "Benediktenwand ist die nähere Nordwand.",
        gear: ["50-m-Seil", "Schlingen", "Helm"]
      }
    }),
    pack({
      id: "unnuetz-nord",
      rank: 70,
      name: "Unnütz north terrain",
      wall: "Unnütz",
      massif: "Rofan / Achenkirch",
      day: "sun",
      dayLabel: "Sun · 38 min",
      drive: "0:35–0:50",
      via: "B13 / Achenpass / Achenkirch",
      aspect: "N",
      grade: "UIAA 4",
      gradeNote: "Closest Achensee limestone from Tölz. Mixed mountain / short MSL. Confirm a named line in a current topo.",
      pitches: "short alpine",
      protection: "alpine",
      protectionNote: "Not a famous bolt grid. Take a real topo.",
      why: "38 minutes, north side of the valley. Thin card — use only with a guidebook line.",
      approach: "Achenkirch, north flanks of Unnütz.",
      descent: "Valley paths.",
      gear: ["50–60 m rope", "Draws, slings", "Helmet"],
      weekend: "Sunday close-north if you have a named topo.",
      dont: ["Invent a line without a topo"],
      neighbor: "Rotspitz is the documented high north 5b.",
      topoPage: "https://www.climbers-paradise.com/kletterregionen/achensee/mehrseillaengen/",
      topoImg: ROF,
      map: "https://www.openstreetmap.org/#map=13/47.527/11.706",
      lat: 47.527,
      lng: 11.706,
      photos: [ROF_M],
      de: {
        dayLabel: "So · 38 Min.",
        via: "B13 / Achenpass / Achenkirch",
        why: "38 Minuten, Nordseite des Tals. Dünne Karte — nur mit Führerlinie.",
        gradeNote: "Nächster Achensee-Kalk ab Tölz. Gemischt Bergtour und kurze Mehrseillängen.",
        protectionNote: "Keine dichte Absicherung. Echtes Topo mitnehmen.",
        approach: "Achenkirch, Nordflanken des Unnütz.",
        descent: "Talwege.",
        weekend: "Sonntag nah-Nord mit benanntem Topo.",
        dont: ["Keine Linie ohne Topo erfinden"],
        neighbor: "Rotspitz ist die dokumentierte hohe Nord-5b.",
        gear: ["50–60-m-Seil", "Exen, Schlingen", "Helm"]
      }
    })
  ];

  /* 30 more compact cards to reach 100. Same honesty rules. */
  const compact = [
    ["glaswand", 71, "Glaswand", "Glaswand", "Tölzer Land", "sun", "NW", "UIAA 5", "1–2", "plaisir", "0:20–0:35", "B472", 47.7, 11.42, "Local Tölzer Land. Short sport, pick NW if hot."],
    ["hohenburg", 72, "Hohenburg", "Hohenburg", "Tölzer Land", "sun", "mixed", "UIAA 5", "1–2", "plaisir", "0:20–0:35", "B472", 47.72, 11.5, "Local crag. Sunday backup."],
    ["daffensteine", 73, "Daffensteine", "Daffensteine", "Jachenau", "sun", "N", "UIAA 5", "1–2", "alpine-bolted", "0:25–0:40", "Jachenau", 47.6, 11.43, "Jachenau rock, often north-ish. Short."],
    ["schreistein", 74, "Schreistein", "Schreistein", "Mangfallgebirge", "sun", "mixed", "UIAA 5", "1–2", "plaisir", "0:35–0:50", "Tegernsee", 47.7, 11.78, "Stadler crag. Short sport."],
    ["jachenau-crag", 75, "Jachenau crag", "Jachenau", "Bayerische Voralpen", "sun", "mixed", "UIAA 5", "1–2", "plaisir", "0:25–0:40", "B13 / Jachenau", 47.606, 11.433, "On the way to Benediktenwand. Short."],
    ["wendelstein-ost", 76, "Wendelstein Ost", "Wendelstein", "Bayerische Voralpen", "sun", "E", "UIAA 4", "several", "alpine", "0:50–1:10", "Bayrischzell", 47.703, 12.012, "East mountain routes. Morning only. Not a bolt grid."],
    ["rotwand-spitzing", 77, "Rotwand terrain", "Rotwand", "Spitzingsee", "sat", "N", "UIAA 3–4", "alpine ridge", "alpine", "0:45–1:00", "Spitzingsee", 47.665, 11.888, "North-ish mountain terrain. Close. Not plaisir."],
    ["laber-ammergau", 78, "Laber crag", "Laber", "Ammergau", "sat", "mixed", "UIAA 5–6", "1–2", "plaisir", "0:45–1:05", "Oberammergau", 47.597, 11.064, "On the way west. Sport. Check aspect."],
    ["krottenkopf", 79, "Krottenkopf", "Krottenkopf", "Estergebirge", "sat", "N", "UIAA 4", "alpine", "alpine", "0:50–1:10", "Garmisch / Oberau", 47.53, 11.16, "North-ish mountain. Alpine, not sport."],
    ["tegelberg-vf", 80, "Tegelberg", "Tegelberg", "Ammergau / Schwangau", "sat", "mixed", "via-ferrata", "via ferrata", "via-ferrata", "1:20–1:40", "B472 / B17", 47.57, 10.756, "Mostly via ferrata. Not a multi-pitch sport answer."],
    ["seeben-sektor", 81, "Seebenwände garden", "Seebenwände", "Mieminger", "sat", "N", "UIAA 6", "1–3", "plaisir", "1:10–1:25", "B13 / Ehrwald", 47.421, 10.957, "True north plaisir. Most lines at or over 6. Pick carefully."],
    ["ferchensee-sektor", 82, "Ferchensee MSL", "Gamsanger / Ferchensee", "Wetterstein", "sat", "N", "UIAA 5–6", "several", "alpine-bolted", "0:55–1:10", "B13 / Mittenwald", 47.44, 11.25, "Same kar as Rabnhoamat. Pick a line under 6."],
    ["kampen-ostwand", 83, "Kampenwand Ostwand", "Kampenwand", "Chiemgauer Alpen", "sun", "E", "UIAA 4b", "2–3", "alpine", "1:00–1:20", "Kampenwandbahn", 47.754, 12.37, "East. Morning sun. Sunday-east logistics."],
    ["kampen-sued", 84, "Kampenwand Südwand", "Kampenwand", "Chiemgauer Alpen", "sun", "S", "UIAA 5", "2–4", "alpine-bolted", "1:00–1:20", "Kampenwandbahn", 47.753, 12.367, "Famous south. Heat reject."],
    ["scheffauer-west", 85, "Scheffauer Westabstieg lines", "Scheffauer", "Kaisergebirge", "sat", "NW", "UIAA 4", "several", "alpine", "1:00–1:20", "Kaindlhütte", 47.557, 12.174, "West/NW of the big north face. Alpine."],
    ["predigerstuhl", 86, "Predigtstuhl Tegernsee", "Predigtstuhl", "Tegernsee", "sun", "N", "UIAA 4", "short alpine", "alpine", "0:25–0:40", "Tegernsee", 47.712, 11.758, "Local north-ish rock / terrain. Thin card."],
    ["risserkogel", 87, "Risserkogel", "Risserkogel", "Tegernsee", "sat", "N", "UIAA 3–4", "alpine", "alpine", "0:40–0:55", "Sutten", 47.638, 11.79, "Neighbor of Plankenstein. Mountain route."],
    ["seekarkreuz", 88, "Seekarkreuz", "Seekarkreuz", "Lenggries", "sun", "mixed", "UIAA 2–3", "scramble", "alpine", "0:20–0:35", "Lenggrieser Hütte", 47.64, 11.62, "Mostly hiking / I–II. Not a multi-pitch answer."],
    ["herzogstand-fels", 89, "Herzogstand rock", "Herzogstand", "Kochel", "sun", "N", "UIAA 4", "1–2", "alpine", "0:25–0:35", "Kochel", 47.653, 11.368, "Local north-ish. Short. Confirm a named line."],
    ["jochberg-fels", 90, "Jochberg", "Jochberg", "Walchensee", "sun", "mixed", "UIAA 3", "scramble", "alpine", "0:35–0:50", "Walchensee", 47.595, 11.345, "Mostly hiking. Low style score."],
    ["karwendelbahn-msl", 91, "Karwendel north MSL", "Westliche Karwendelspitze", "Karwendel", "sat", "N", "UIAA 5", "several", "alpine", "1:05–1:25", "Mittenwald Karwendelbahn", 47.43, 11.276, "High, north, Bahn. Alpine, not plaisir."],
    ["hollental-msl", 92, "Höllental walls", "Höllental", "Wetterstein", "sat", "N", "UIAA 5", "several", "alpine", "0:55–1:15", "B13 / Grainau", 47.475, 11.024, "True north valley. Alpine. Confirm the line."],
    ["schachen-msl", 93, "Schachen walls", "Schachen", "Wetterstein", "sat", "N", "UIAA 5", "several", "alpine", "0:55–1:10", "Mittenwald / Ferchensee", 47.42, 11.24, "Same approach as Rabnhoamat. Pick ≤6. Thin card — confirm bolts."],
    ["kenzen-nord", 94, "Kenzen north", "Ammergau north walls", "Ammergauer Alpen", "sat", "N", "UIAA 5", "several", "alpine", "1:10–1:25", "Halblech / Kenzenhütte", 47.58, 10.84, "Same valley as Geiselstein. Alpine north."],
    ["vorderkaiserfelden", 95, "Vorderkaiserfelden MSL", "Zahmer Kaiser", "Kaisergebirge", "sun", "mixed", "UIAA 5", "several", "mixed", "1:25–1:40", "Kaisertal / hut", 47.598, 12.219, "Hut-based. Confirm aspect. Longer than Sparchen."],
    ["steinplatte-sued", 96, "Steinplatte", "Steinplatte", "Waidring", "sat", "S", "UIAA 5–6", "several", "plaisir", "1:50–2:15", "A8 / Waidring", 47.63, 12.57, "SW–SE plaisir. ~2 h and sunny. Heat reject."],
    ["ruchenkoepfe-sued", 97, "Ruchenköpfe", "Ruchenköpfe", "Spitzingsee", "sat", "S", "UIAA 5", "several", "alpine-bolted", "0:45–1:00", "Spitzingsee", 47.67, 11.9, "Famous south. Heat reject. Close though."],
    ["untersberg", 98, "Untersberg", "Untersberg", "Berchtesgadener Alpen", "sat", "N", "UIAA 5", "several", "alpine", "1:50–2:20", "A8 / Berchtesgaden", 47.63, 12.973, "True north possible. Drive at the edge."],
    ["mann-oder-memme", 99, "Mann oder Memme", "Buchstein Südwand", "Tegernsee", "sat", "S", "UIAA 6", "several", "alpine-bolted", "0:35–0:50", "Tegernseer Hütte", 47.6257, 11.8015, "South neighbor of Südwandschmankerl. Heat reject. At the cap."],
    ["via-weissbier", 100, "Via Weißbier", "Buchstein Südwand", "Tegernsee", "sat", "S", "UIAA 6", "several", "alpine-bolted", "0:35–0:50", "Tegernseer Hütte", 47.626, 11.8016, "Rap in from the hut terrace. South, steep, at the cap."]
  ].map(([id, rank, name, wall, massif, day, aspect, grade, pitches, protection, drive, via, lat, lng, why]) => {
    const over = /via-ferrata|7\+|8−|over/i.test(grade) || protection === "via-ferrata";
    const sun = day === "sun";
    return {
      id,
      rank,
      overGrade: over,
      name,
      wall,
      massif,
      day,
      dayLabel: sun ? `Sun · ${aspect}` : `Sat · ${aspect}`,
      drive,
      via,
      aspect,
      grade,
      gradeNote: why,
      pitches,
      protection,
      protectionNote: protection === "plaisir" ? "Sport / rappel-ready." : protection === "via-ferrata" ? "Via ferrata — not a multi-pitch sport answer." : "Confirm bolts live.",
      why,
      approach: `From Bad Tölz via ${via}.`,
      descent: "Per topo / walk-off.",
      gear: protection === "via-ferrata" ? ["Via-ferrata kit", "Helmet"] : ["60 m rope", "10–12 draws", "Helmet"],
      weekend: sun ? "Sunday short / backup." : "Saturday if the match % is still honest.",
      dont: ["Treat this compact card as a full topo", "Ignore aspect on a heat day"],
      neighbor: "See the named lines on the same massif.",
      topoPage: "https://www.thecrag.com/en/climbing/germany/area/400556487",
      topoImg: "",
      wallImg: "",
      map: `https://www.openstreetmap.org/#map=13/${lat}/${lng}`,
      lat,
      lng,
      photos: [],
      de: {
        dayLabel: sun ? `So · ${aspect}` : `Sa · ${aspect}`,
        via,
        why,
        gradeNote: why,
        protectionNote: protection === "plaisir" ? "Sport / Abseilstände." : protection === "via-ferrata" ? "Klettersteig — keine Sport-Mehrseillänge." : "Haken vor Ort prüfen.",
        approach: `Ab Bad Tölz über ${via}.`,
        descent: "Laut Topo / zu Fuß.",
        weekend: sun ? "Sonntag kurz / Backup." : "Samstag, wenn der Match noch ehrlich ist.",
        dont: ["Diese Kurzkarte nicht als volles Topo", "Exposition an einem Hitzetag nicht ignorieren"],
        neighbor: "Die benannten Linien im selben Massiv.",
        gear: protection === "via-ferrata" ? ["Klettersteigset", "Helm"] : ["60-m-Seil", "10–12 Exen", "Helm"]
      }
    };
  });

  const all = extra.concat(compact);
  window.ROUTES = window.ROUTES.concat(all);
  window.ROUTE_I18N = window.ROUTE_I18N || { de: {} };
  all.forEach((r) => {
    if (r.lat) window.ROUTE_COORDS[r.id] = { lat: r.lat, lng: r.lng };
    if (r.photos) window.ROUTE_PHOTOS[r.id] = r.photos;
    window.ROUTE_CROWD[r.id] = r.crowd || { sat: 2, sun: 1, jam: 22 };
    if (r.de) window.ROUTE_I18N.de[r.id] = r.de;
    delete r.lat;
    delete r.lng;
    delete r.photos;
    delete r.crowd;
    delete r.de;
  });
})();
